### ISSUE TITLE
User Profile Editing – Opening Role Agreement and Submit

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#100]
- [x] When click on the agreement to read, there is a button to agree the statement. If I clicked on this button, the agreement window has to be closed and the concerned agreement checkbox must be checked. But it does not affect the checkbox. So, I have to check the checkbox again.
- [x] there is no buttons for submit or cancel the modifications.
![image](https://user-images.githubusercontent.com/11155105/38186929-243ccae2-365e-11e8-986f-64908e7f9cdc.png)
![image](https://user-images.githubusercontent.com/11155105/38186932-275f5ba4-365e-11e8-9792-373f4d5110f1.png)

**Comment by ahmedelbougha** [comment]
The buttons for submit/cancel are already there.

**Comment by HeshamHassan** [comment]
When loging in as a user (not admin) the buttons for submit/cancel are not there.
![image](https://user-images.githubusercontent.com/11155105/38194834-b7b4f596-3682-11e8-81b5-94a3d65e8a59.png)

**Comment by mahmoud-hussien1** [comment]
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/95
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/97

**Comment by ahmedelbougha** [comment]
- User registration
- User edit profile
- Admin new user
- Admin edit user

**Comment by ahmedelbougha** [comment]
done
