### ISSUE TITLE
Home menu at Header

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#101]
URL: http://skillsbuilderpro.com/ 
Subject: When click on Home at the header menu, it leads to wrong URL: http://skillsbuilderpro.com/www.skillsbuilderpro.com 
![image](https://user-images.githubusercontent.com/11155105/38188095-03423c32-3663-11e8-97e7-44da403875c8.png)

![image](https://user-images.githubusercontent.com/11155105/38188099-06bb5d3a-3663-11e8-9706-4e8ed81e2dd1.png)

**Comment by ahmedelbougha** [comment]
this issue can be fixed from CMS, it seems like the content team put the wrong URL for that menu.

**Comment by Ali-Galal** [comment]
@HeshamHassan For your immediate action please
