### ISSUE TITLE
Courses Lay out page 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#102]
The layout of all courses pages need to be reviewed and outline does not appear in the front end.

**Comment by ahmedelbougha** [comment]
Course outlines are displayed normal ex. http://skillsbuilderpro.com/courses/more/1
In regard to layout, would you please send more details about what you want to do?

**Comment by Ali-Galal** [comment]
Course outlines are not displayed normally ex. http://skillsbuilderpro.com/courses/more/8
the same page in CMS http://skillsbuilderpro.com/courses/outlines/8

**Comment by HeshamHassan** [comment]
The outline is inactive in CMS. when make activation, it works probably.

**Comment by ahmedelbougha** [comment]
done
