### ISSUE TITLE
Agreement is not Aligned

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#103]
**URL:** http://skillsbuilderpro.com/users/edit/14
**Subject:** The agreement is not aligned with its role. This issue appears when log in with any user, not only with the admin log in.
![image](https://user-images.githubusercontent.com/11155105/38195433-24072e6e-3686-11e8-978a-0f372817496e.png)
![image](https://user-images.githubusercontent.com/11155105/38195436-263b3a9a-3686-11e8-8020-f905181801c9.png)

**Comment by ahmedelbougha** [comment]
done
