### ISSUE TITLE
Remove the " X " sign in the website

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#104]
As per Eng. Ali, 
Remove the " X " sign in all pages of the website.
![image](https://user-images.githubusercontent.com/11155105/38240436-41e9ec5c-3738-11e8-9c51-8f491bb6f4c1.png)

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/94

**Comment by ahmedelbougha** [comment]
done
