### ISSUE TITLE
Call to action 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#105]
Dear Ahmed,

Please note that the call to action associated with the PDF flyer is purchase now, while it should be Download now

**Comment by ahmedelbougha** [comment]
@badr4php  would you please take care of this?

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/93

**Comment by ahmedelbougha** [comment]
merged, done
