### ISSUE TITLE
Remove Arabic Icon

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#107]
@ahmedelbougha kindly hide the Arabic icon till we finish the arabic version

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by Ali-Galal** [comment]
third reminder

**Comment by ahmedelbougha** [comment]
Date: 30/04/2018

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
Moving to new git repository
