### ISSUE TITLE
User Menu is unavailable

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#108]
**URL:** http://skillsbuilderpro.com/
**Subject:** When sign in with any role, I cannot find the “User” menu.
![image](https://user-images.githubusercontent.com/11155105/38300558-c722c20e-3805-11e8-851b-0b9f1d236eb5.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/106

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by ahmedelbougha** [comment]
merged
