### ISSUE TITLE
Take this Course

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#109]
The tab link should be linked to the registration form if the visitor is not registered and to the shopping cart if he is

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Would you please check this tomorrow and confirm it is fixed?

**Comment by LamiaSalah** [comment]
@ahmedelbougha The tab goes to the calendar page when I'm signed in, it should go to the estore

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
This is the correct behavior, you cannot reserve a seat directly into course, but you have to reserve the seat in course event, which happens only from calendar.

**Comment by Ali-Galal** [comment]
Course events have different price for each
