### ISSUE TITLE
Tabs at the top of  a course page

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#110]
They should be ILT, AudioBook and Elearning instead of ALL, ILT and Audio

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
We will change Audio to AudioBook En Shaa Allah.
In regard to the rest of you requirements above, we need to have Tab (All) otherwise the user cannot clear the filter, and (E-learning) is currently not available in SkillsBuilder, so we can add it after adding it to backend.

**Comment by ahmedelbougha** [comment]
done

**Comment by LamiaSalah** [comment]
@ahmedelbougha please delete the three tabs at the top of each course page

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/40025187-78ff49f0-57d9-11e8-8e57-bbfcf037b964.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha any updates?

**Comment by badr4php** [comment]
@here Done
