### ISSUE TITLE
Registration 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#111]
The registration fields should be separated between the Arabic and English section, currently, all are added on one page and format need to be fixed

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is an enhancement, please confirm to work on estimation

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please confirm?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Another kind reminder.

**Comment by Ali-Galal** [comment]
Hold it in mean while
