### ISSUE TITLE
No access to Flipping Book page.

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#113]
**URL:** http://skillsbuilderpro.com/courses/more/12
**Path:** Learning Paths > Small business builder> Building an Online Business> Course Resources
**Subject:** 
On the course resources, when click on “Purchase now”:
![image](https://user-images.githubusercontent.com/11155105/38466066-4718d542-3b2c-11e8-8a69-111bde9cedc2.png)

I got the following message:
![image](https://user-images.githubusercontent.com/11155105/38466067-49cd8468-3b2c-11e8-962b-239883cc2de5.png)

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
The same issue 
the screen shot of this issue today:
![image](https://user-images.githubusercontent.com/11155105/38856169-5db99aee-422e-11e8-9067-3cc561dbbbab.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please provide us with complete scenario.
Also, please send us the username/password your are using.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
- Log in (username: user2 / password: 123456789)
- Click on Learning Paths menu
- Click on Small business builder
- Click on Building an Online Business
- Click on Course Resources
- Click on Trainer Flipping Book	
- Click on Purchase now

_Note: Any users I create has password: 123456789_

**Comment by ahmedelbougha** [comment]
Thanks @HeshamHassan 
@badr4php would you please check?

**Comment by ahmedelbougha** [comment]
@badr4php 
I think the USER role doesn't have privileges to use this, correct?

**Comment by badr4php** [comment]
@ahmedelbougha  Yes,only you need to change privileges  for each role  from admin area

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Please check the permissions that you want to give to User role in admin area.

**Comment by ahmedelbougha** [comment]
No need to code fix.
