### ISSUE TITLE
Flipping Book for Students and Trainers.

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#114]
**Subject:** 
The Flipping Book has 2   sections. First section is used for student courses. Second section is used   for trainer courses.   How to separate them at the   website?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is a new requirement, please confirm that you need it to proceed with time/cost estimation.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we are testing it now, just wait till we try it

**Comment by Ali-Galal** [comment]
@ahmedelbougha yes, kindly send to me the time and cost, knowing that I just need to remove the restriction of uploading more than one flipping book for the same course

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
We will create 2 different types of Flipping Book resources:
1- Trainer Flipping Book
2- Student Flipping Book
each of them shall have only one upload (same old restriction), so you can upload both types for the same course.
Time estimation: 8 hours
Estimated date: 12/04/2018

**Comment by Ali-Galal** [comment]
Approved

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/102

**Comment by ahmedelbougha** [comment]
done
