### ISSUE TITLE
Take this course

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#115]
**URL:** http://skillsbuilderpro.com/courses/calendar
**Path:** Learning Paths> Small Business Builder> Building a Consulting Business> More> TAKE THIS COURSE
**Subject:** When I press “Take This Course” button, it diverts me to the following page (Course Calendar) which has all courses. And I have to search again for my concern course.
![image](https://user-images.githubusercontent.com/11155105/38496927-f2c548cc-3c07-11e8-9087-7b1cc90a0bec.png)

 - [ ] Filter this page (Course Calendar) to focus on only the chosen course.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/105

**Comment by ahmedelbougha** [comment]
done
