### ISSUE TITLE
Invalid Redirection in Course Calendar Page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#116]
**URL:** http://skillsbuilderpro.com/courses/calendar
**Path:** Learning Paths> Small Business Builder> Building a Consulting Business> More> TAKE THIS COURSE
**Subject:** In (Course Calendar) page, when click on “More..” link, the link leads to a page of another course.
![image](https://user-images.githubusercontent.com/11155105/38497085-8d0d8796-3c08-11e8-9be8-7359d0e2b33f.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/103

**Comment by ahmedelbougha** [comment]
done
