### ISSUE TITLE
Learning Path Page Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#117]
**URL:**http://skillsbuilderpro.com/categories/courses/3
**Path:**Learning Paths> Career Skills Builder>
**Subject:**
There is an inactive course in “Career Skills Builder” 
![image](https://user-images.githubusercontent.com/11155105/38556439-5a216896-3cd2-11e8-9fe5-6c42523c38d9.png)
And the course appears in the front-end as shown below:
![image](https://user-images.githubusercontent.com/11155105/38556446-62108604-3cd2-11e8-9747-ff69a2fea036.png)

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/98

**Comment by ahmedelbougha** [comment]
done
