### ISSUE TITLE
SBP-118 : Fix Contact us page 

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/skillsbuilder#118]
use this address for the USA:
7610 W Hwy 71

Suite F

Austin TX, 78735

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/100

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Needs some fixes for map locations

**Comment by ahmedelbougha** [comment]
done

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Still need some fixes in Arabic edition.

**Comment by ahmedelbougha** [comment]
done.
