### ISSUE TITLE
SBP -119 : Course's page enhancement 

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/skillsbuilder#119]
- [x] You’ll change Take this Course tab to ‘Find out more’

- [x] Remove the Calendar tab

- [x] You’ll keep only the two tabs Course Outline and Resources invisible until visitor registers.

- [x] After registration they can access the above tabs

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/99

**Comment by LamiaSalah** [comment]
Confirmed, all changes above are required.

**Comment by ahmedelbougha** [comment]
done
