### ISSUE TITLE
SBP-120 : Add Section "add an email" for course event notification.

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/skillsbuilder#120]
Section where they can add an email to get notified of available dates.

**Comment by ahmedelbougha** [comment]
@badr4php @mahmoud-hussien1 
Did we fix this?

**Comment by ahmedelbougha** [comment]
To be discussed with @Ali-Galal

**Comment by Ali-Galal** [comment]
@HeshamHassan add this to the enhancement file
