### ISSUE TITLE
SBP-121 :Display course events dates in course page

### ISSUE THREAD

**Issue by badr4php** [camelcasetechsd/skillsbuilder#121]
- [x]  Add course dates (Under the course photo)

- [x] Add a “public dates” and “private date” section

- [x]  Dates clicked should lead to checkout

- [x] We are currently full

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/101

**Comment by ahmedelbougha** [comment]
done
