### ISSUE TITLE
eStore Logging in Problem

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#122]
**URL:** http://skillsbuilderpro.com/estore/
**Subject:**
After logging in and when click on eStore at the header, I got the eStore page without logging in! and it asks to sign in again.
When click on Sign in button, it redirects me to the home page: SkillsBuilderPro.com 
![image](https://user-images.githubusercontent.com/11155105/38779599-50af7b0e-40d3-11e8-937a-f7e01ba28e28.png)

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/113

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by badr4php** [comment]
Done

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.
