### ISSUE TITLE
eStore Layout

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#123]
**URL:** http://skillsbuilderpro.com/estore/
**Subject:**
- [ ] The eStore layout need to be completely fixed (logo, tabs, commands and content of the page for each course)
- [ ] The big white area need to be reduced a bit
![image](https://user-images.githubusercontent.com/11155105/38792653-c3ee2a88-4156-11e8-88cf-7e7dfd8d29e9.png)

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by Ali-Galal** [comment]
2nd Reminder

**Comment by Ali-Galal** [comment]
@HeshamHassan FYA

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
This was 4 days ago? did you review the layout? I want to close this issue.

**Comment by HeshamHassan** [comment]
Ok 
Done!
