### ISSUE TITLE
Front End - Resources Page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#124]
**URL:** http://skillsbuilderpro.com/courses/more/3
**Path:** Learning Path> Small Business Builder> Managing Projects: First Steps First> More> Course Resources
**Subject:** 
- [x] The resources page shows the name of a learning path at the top, it should show the course name.
![image](https://user-images.githubusercontent.com/11155105/38792697-0433c0a8-4157-11e8-998b-06d4231fa800.png)

**Comment by ahmedelbougha** [comment]
done
