### ISSUE TITLE
CMS Course Resources

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#125]
**URL:** http://skillsbuilderpro.com/courses/resources/edit/3
**Path:** Backend> course> courses> Recourses> create new resource> Type
**Subject:**
As per my discussion with Lamia, the type list has duplicated values. They are the same use:
•	Trainer guide & trainer flipping book
•	Student guide & student flipping book
- [ ] Remove (trainer flipping book) and remove (student flipping book) from the list
![image](https://user-images.githubusercontent.com/11155105/38792768-4d4bab2a-4157-11e8-864b-978e3f43b8fd.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal @LamiaSalah 
You mean to remove Trainer Guide and Student Guide? or to remove Trainer and Student Flipping books?
Please confirm!

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please take care this will affect the course page if any of them contains old Trainer or Student Guides.
Also, it will affect category pages filter (ILT) that should be changed to show the Flipping books. Please confirm.

**Comment by HeshamHassan** [comment]
@Ali-Galal @ahmedelbougha 

Please @LamiaSalah Confirm that : _Remove Trainer and Student Flipping books_

**Comment by ahmedelbougha** [comment]
@badr4php 
As per my call with @LamiaSalah, it's confirmed to rename Trainer Guide and Student Guide and rename the Flipping Book resources.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/107

**Comment by LamiaSalah** [comment]
Confirmed Ahmed

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by ahmedelbougha** [comment]
@HeshamHassan the function is already running! we will remove the old resources types today En Shaa Allah.

**Comment by ahmedelbougha** [comment]
this issue has been fixed
