### ISSUE TITLE
Customer Journey

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#126]
After clicking find out more on the course's page, the visitor should go to register then to the course outline.
a tab with Take this course should be added on the calendar page and outline page

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/109

**Comment by LamiaSalah** [comment]
Any updates on this issue?

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by ahmedelbougha** [comment]
merged

**Comment by LamiaSalah** [comment]
@ahmedelbougha Please note that course outline disappeared from all courses

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
I can see the outline of the course normally. Are you logged in or not?

![skills builder pro](https://user-images.githubusercontent.com/8982139/39404947-7205954e-4b9c-11e8-9333-78fc6b6215aa.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha yes, but can't see them

**Comment by Ali-Galal** [comment]
@LamiaSalah Hesham can see the outline as the attached screenshot, kindly inform us if the issue still occurs or has been settled

**Comment by LamiaSalah** [comment]
@Ali-Galal issue resolved
