### ISSUE TITLE
Banner Data

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#127]
**URL:**
**Subject:**
- [x] Banner data must be changed
![image](https://user-images.githubusercontent.com/11155105/38873299-15952b54-425e-11e8-9385-a87d59fc13f4.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please send specific changes that you need to include in banner.

**Comment by LamiaSalah** [comment]
Dear Ahmed,

Messages are all sent to you earlier in word doc by me dated 10 April

Regards,

Lamiaa

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
This is the text you sent:
```
Photo 1: “Education is the most powerful weapon which you can use to change the world.” ― Nelson Mandela
Photo 2: Change your world with Skills Builder Pro
Photo 3: Job skills education begins with Skills Builder Pro
Photo 4: Start your bright future now 
```
Would you please specify which text put in which part? For example:

  - Photo1: 
    - Upper text “Education is the most powerful weapon which you can use to change the world.”
    - Lower text "Nelson Mandela"

**Comment by LamiaSalah** [comment]
Yes, the same as you wrote it down, all other text will be in one line and will be put in order with the current photos.

Please use the info in the same doc for the footer info.

Regards,

Lamiaa

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah banner text will be as below.

![screenshot from 2018-04-18 15 20 47](https://user-images.githubusercontent.com/35919348/38934611-82ded21e-431c-11e8-9c82-eee27d9b288f.png)
![screenshot from 2018-04-18 15 21 54](https://user-images.githubusercontent.com/35919348/38934613-83091650-431c-11e8-8bfc-6ea9811e1390.png)
![screenshot from 2018-04-18 15 22 12](https://user-images.githubusercontent.com/35919348/38934614-8338fafa-431c-11e8-83f6-8a83ad45c3d3.png)
![screenshot from 2018-04-18 15 22 25](https://user-images.githubusercontent.com/35919348/38934615-836aa0a0-431c-11e8-8b47-a9fa9989e544.png)

**Comment by LamiaSalah** [comment]
That's ok, but please make the font of Nelson Mandela smaller than the other font and in italics if possible

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah ok.

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/114

**Comment by LamiaSalah** [comment]
Hi, As per my call with Ahmed please find the new text to be added:

Photo 1: Learn the most practical, in-demand job skills employers seek. Explore more than 100 disciplines in accredited courses.
Photo 2: Learn the skills you need, qualify for top jobs, and build your career with Skills Builder Pro 
Photo 3: Elevate your employees’ productivity and effectiveness, develop your workforce skills and achieve greater prosperity for all
Photo 4: Enrich your portfolio and increase your competitive advantage, reach more people and increase your revenue

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah  is that you want?
![screenshot from 2018-04-22 18 48 31](https://user-images.githubusercontent.com/35919348/39097545-0afc58e4-465e-11e8-8208-fa8fc31e1080.png)
![screenshot from 2018-04-22 18 48 47](https://user-images.githubusercontent.com/35919348/39097546-0b2dccf8-465e-11e8-921c-b653a5e713a7.png)
![screenshot from 2018-04-22 18 48 57](https://user-images.githubusercontent.com/35919348/39097547-0b5caa6e-465e-11e8-8b0f-013b5da9a47f.png)
![screenshot from 2018-04-22 18 49 08](https://user-images.githubusercontent.com/35919348/39097548-0b8a86fa-465e-11e8-9d6d-e5560d2251a7.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan @LamiaSalah 
In order to finish this ticket, we need your confirmation about the above.

**Comment by LamiaSalah** [comment]
Confirmed

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/114

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by ahmedelbougha** [comment]
merged

**Comment by Ali-Galal** [comment]
@ahmedelbougha we are ok with the Text but the style is not ok, 

@LamiaSalah @ahmedelbougha we need to talk about this

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah 
Please note that this needs some 2 level text to be shown as expected.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Attached is the text for the header with the kay out and links 
[Header text.docx](https://github.com/camelcasetechsd/skillsbuilder/files/1998295/Header.text.docx)

**Comment by LamiaSalah** [comment]
@ahmedelbougha any updates?

**Comment by mahmoud-hussien1** [comment]
https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/21/issue-127-change-banner-data/diff

**Comment by badr4php** [comment]
@here Merged

**Comment by Ali-Galal** [comment]
@LamiaSalah please confirm

**Comment by LamiaSalah** [comment]
@Ali-Galal confirmed. Only on the second photo, please remove the comma in the first line.

**Comment by ahmedelbougha** [comment]
today

**Comment by Ali-Galal** [comment]
@LamiaSalah done, please confirm

**Comment by LamiaSalah** [comment]
@Ali-Galal Confirmed
