### ISSUE TITLE
Contact email

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#128]
Please change the email in contact us page to info@skillsbuilderpro.com

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/112

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
Not yet proceed...
![image](https://user-images.githubusercontent.com/11155105/38935099-18bcbce8-4326-11e8-95f5-a43eee6516a8.png)

Did you publish it?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
What do you mean?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Yes, it's published, sorry I didn't get you for first time.
