### ISSUE TITLE
Adding Links to Footer

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/skillsbuilder#129]
Add the following 5 columns to footer instead of current ones:
1- About SBP
  - Corporate Profile 
  - Membership
  - How Can SBP help you 
  - Value Pack 
  - Our Customers
  - Booking 

2- Learning Paths
  - Small Business Builder
  -  Personal Skills Builder   
  -  Career Skills Builder
  -  Workplace Skills Builder
  -  Marketing Pro  
  -  Sales Pro
  -  Job Skills Pro 
  -  Talent Development Pro  
  -  Management Pro 

3- Training
  -  Courses 
  -  Why Train with SBP 
  -  Trainer’s Hub 
  -  Certified Trainers
  -  ATC Program 
  -  LMS Portal

4- Estore

5- Contact Us

**Comment by LamiaSalah** [comment]
[Document1.docx](https://github.com/camelcasetechsd/skillsbuilder/files/1937805/Document1.docx)
Attached is the content for the full footer items with the correct order.
AS for the corporate profile link, here it is http://skillsbuilderpro.com/About/corportate_profile

**Comment by mahmoud-hussien1** [comment]
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/116

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
The last document you sent contains 6 columns instead of 5 columns, which may affect the design of the template.
Please remove one column, or confirm that you need 6 columns even with design affected.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Keep them 5 with removing contact us column

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by ahmedelbougha** [comment]
merged

**Comment by HeshamHassan** [comment]
Some links are not working:

- About 
- Learning Paths
- Training
- Servises
- Membership
- Value Pack
- Booking
![image](https://user-images.githubusercontent.com/11155105/39406272-de89a8fc-4bbc-11e8-8f96-39a69ea504e7.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan  URL needed for those links:

- About

- Learning Paths


- Training

**Comment by Ali-Galal** [comment]
@ahmedelbougha Kindly remove the hyperlink from the following:
About
Learning Paths
Training
Services
eStore

**Comment by ahmedelbougha** [comment]
30/04/2018

**Comment by HeshamHassan** [comment]
Any update??

**Comment by ahmedelbougha** [comment]
merged
