### ISSUE TITLE
Content for each Learning Path

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#130]
The content added for each learning path is removed and not shown on homepage, though it's added on the CMS

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/38984256-e09cd45c-43ce-11e8-9b0f-9a3b7659d865.png)
![image](https://user-images.githubusercontent.com/11155105/38984341-16180a7a-43cf-11e8-982f-6eba80feeb9b.png)

**Comment by Ali-Galal** [comment]
@ahmedelbougha I need your prompt action

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by ahmedelbougha** [comment]
This is fixed and I informed Lamia today about it.
