### ISSUE TITLE
Size of flipping book file

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#131]
Please note that there's one file for one of the courses for flipping book that does not need to be uploaded on the website because of its size that is 215.469 KB

Please advise

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by Ali-Galal** [comment]
duplicated [issue #138 ](138)
