### ISSUE TITLE
Registration button 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#133]
Add Register to be a Trainer button on Trainer's hub page that takes to the registration form

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
You can do this through CMS, @Ali-Galal would you please help with this?

**Comment by LamiaSalah** [comment]
@Ali-Galal 
Please let me know Aly if I can work on it myself

**Comment by Ali-Galal** [comment]
@LamiaSalah send the CMS page's URL to me, I will handle it

**Comment by Ali-Galal** [comment]
@LamiaSalah Check it please, AR & EN

**Comment by LamiaSalah** [comment]
@Ali-Galal Thanks Aly
