### ISSUE TITLE
Course brief undownloadable

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#136]
The course brief in the resources section is not downloadable

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by mahmoud-hussien1** [comment]
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/118
done.

**Comment by Ali-Galal** [comment]
@ahmedelbougha is it done for all resources?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is done for Brief PDF.

**Comment by Ali-Galal** [comment]
@ahmedelbougha as I understood from my team, we faced it in all resources, kindly check from your side.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
You mean you need the Flipping Book to be downloadable? In that case it's better to give @LamiaSalah the option of #139 since it doesn't require the user to wait for long time downloading huge resource like Flipping Book.

**Comment by ahmedelbougha** [comment]
@Ali-Galal Currently we have the following resources:

1- Student Guide  (flipping book)
2- Trainer's Guide  (flipping book)
3- Brief PDF
4- Audio Book (not downloadable)

**Comment by Ali-Galal** [comment]
@LamiaSalah @ahmedelbougha we need a call for this

**Comment by Ali-Galal** [comment]
@LamiaSalah @ahmedelbougha https://global.gotomeeting.com/join/859631773

**Comment by ahmedelbougha** [comment]
merged

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please note that the issue still exists and the brief gives an error message when you click download.

**Comment by LamiaSalah** [comment]
Done
