### ISSUE TITLE
Top Courses 1st picture dimensions.

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#137]
The 1st picture dimensions in the Top Courses is not the same of the other pictures.
- [ ] Fix the picture dimensions. 
![image](https://user-images.githubusercontent.com/11155105/39132623-f07208c6-471a-11e8-84d7-ecaefc65956e.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise the size of the photo to amend it accordingly

**Comment by mahmoud-hussien1** [comment]
PR - http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/120

**Comment by ahmedelbougha** [comment]
merged

**Comment by Ali-Galal** [comment]
@ahmedelbougha still has a problem with the picture stretching

**Comment by HeshamHassan** [comment]
The pictures in the hot courses section at homepage have unsuitable dimensions. Some are stretched and other are shrunk.
![image](https://user-images.githubusercontent.com/11155105/40026792-846263f8-57df-11e8-9c65-ffbd01733944.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
the images uploaded with dims:
width: 1912 pixels
height: 1270 pixels
but it should be with height: 370 px and width: about 325 px.

**Comment by Ali-Galal** [comment]
@LamiaSalah Kindly change the size and upload it again

**Comment by LamiaSalah** [comment]
@Ali-Galal I don't have access to change anything on the home page also having the photo with these dimensions will have it pixilated.  Attached is the photo with the original size, could you please help with this? 
![istock-516357942](https://user-images.githubusercontent.com/37042927/40054911-9b47cd9e-5846-11e8-826e-615c13b42490.jpg)

**Comment by LamiaSalah** [comment]
@Ali-Galal 
![325x370](https://user-images.githubusercontent.com/37042927/40056072-7bfa8770-584a-11e8-973a-5aae12d672e9.jpg)

**Comment by Ali-Galal** [comment]
@LamiaSalah I think CamelCase will need the 4 pictures in the same size, kindly proceed.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Please advise the photos names on the system so I can edit them.

**Comment by LamiaSalah** [comment]
@ahmedelbougha @Ali-Galal Attached are the other 3 photos with the required dimensions 
![1](https://user-images.githubusercontent.com/37042927/40358831-e224c5c6-5dc0-11e8-9421-a9be21225ca0.jpg)
![2](https://user-images.githubusercontent.com/37042927/40358835-e5111f0a-5dc0-11e8-8373-f66d8530d5da.jpg)
![3](https://user-images.githubusercontent.com/37042927/40358837-e6f0aa3e-5dc0-11e8-8973-454590c2fe9f.jpg)

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @LamiaSalah 
I uploaded these images for this time, in the future in case you want to change them again, you need to edit their relevant courses from CMS:
http://skillsbuilderpro.com/courses/edit/12
http://skillsbuilderpro.com/courses/edit/44
http://skillsbuilderpro.com/courses/edit/66
http://skillsbuilderpro.com/courses/edit/80
