### ISSUE TITLE
Flipping book file size

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#138]
There's one file with 215.469 KB that doesn't need to upload on the website.

**Comment by ahmedelbougha** [comment]
You mean you cannot upload it?

**Comment by LamiaSalah** [comment]
yes, it says that the file size is bigger than the capacity

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Did you manage to increase the upload size from the server administration?

**Comment by LamiaSalah** [comment]
Dear Aly,

Could you please advise?

Regards,

Lamiaa

**Comment by Ali-Galal** [comment]
@LamiaSalah Done, kindly re-upload and confirm

**Comment by LamiaSalah** [comment]
@ahmedelbougha The issue still exists

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please check with @Ali-Galal

**Comment by LamiaSalah** [comment]
@Ali-Galal could you please advise?

**Comment by Ali-Galal** [comment]
@LamiaSalah kindly try again
