### ISSUE TITLE
Flipping book preview option in admin

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/skillsbuilder#139]
As per call with @LamiaSalah  admin Flipping book preview link.
@Ali-Galal 
Please advise

**Comment by Ali-Galal** [comment]
Hold it in the meantime, instead of this kindly solve [issue #136](136)

**Comment by Ali-Galal** [comment]
@ahmedelbougha Kindly proceed

**Comment by ahmedelbougha** [comment]
merged

**Comment by Ali-Galal** [comment]
@ahmedelbougha Trainer guide and some of the student guide are not working

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @LamiaSalah , @HeshamHassan 
Please send me an example for both trainer guide and student guide you are uploading, since we are used the example you sent use before and it seems working fine. I'm attaching the example to this ticket.
[SBPTest.zip](https://github.com/camelcasetechsd/skillsbuilder/files/1967896/SBPTest.zip)

**Comment by LamiaSalah** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan The issue is now being fixed (for the Trainer) The problem was with the way the files were compressed.
