### ISSUE TITLE
Private training 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#141]
please make the link to private training on each course page go to the course separately not the full list of courses.

**Comment by ahmedelbougha** [comment]
Fix the page
http://skillsbuilderpro.com/quote/training/private

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/121

**Comment by ahmedelbougha** [comment]
merged
