### ISSUE TITLE
Authorized Training Partner Program

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#142]
**URL:** http://skillsbuilderpro.com/About/Partner_with_SBP/atp_program
**Path:** About> Partner with SBP> ATP Program
**Subject:** The link of “Become an Authorized Training Partner” redirected to new user registration form, while I’m logged on. 
![image](https://user-images.githubusercontent.com/11155105/39252974-7e5af4e6-48af-11e8-8ea6-3c0e3cbb3d6a.png)

This link must:
- [ ] Open the "Create New ATP" form if the user is logged on.
- [ ] Redirect the user to "Login" form if user is not logged.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
The link takes you to New Organization Form if you are logged in and to login page if you are not.
This is already how the link works, so what is the issue?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
After discussion and explaining from @Ali-Galal ... it's ok now
