### ISSUE TITLE
Customer Journey

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#143]
The same issue still exists for the customer journey regarding the course details.
For a new visitor, the steps should be: 

1) More(for seeing course overview) and calendar only
2)find out more (takes him to log in)
3) after logging in, he can see the outlines and resources and download only pdf brief
4) in order to get the trainer's or student's guide he should register

**Comment by ahmedelbougha** [comment]
duplicated issue with #126
