### ISSUE TITLE
preview of courses on each learning paths

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#144]
the preview of each course on each learning path starts with Course overview, which shouldn't be the case. It should start with the content directly. Also the format of the content has some errors in the text

**Comment by Ali-Galal** [comment]
@LamiaSalah kindly remove the "Course Overview" phrases from the CMS

**Comment by LamiaSalah** [comment]
@Ali-Galal if this is deleted from the text, will it be set as standard in all courses' pages above the text? it needs to be there

**Comment by Ali-Galal** [comment]
@LamiaSalah if this the case we have to add it in the Course Overview page 
@ahmedelbougha kindly add the "Course Overview" phrases to the course page structure as a header instead of inserting them in the content.

**Comment by ahmedelbougha** [comment]
ok

**Comment by ahmedelbougha** [comment]
03/05/2018

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/10/sbp144-add-course-overview-phrase-and-its/diff

**Comment by Ali-Galal** [comment]
update?

**Comment by ahmedelbougha** [comment]
sorry, it's merged, but you need to remove the word "Overview" and "موجز الدورة التدريبية" from course body

**Comment by HeshamHassan** [comment]
I removed the "**Course Overview**" and refreshed the page.  but the fixed header: "Course Overview" is not present at the page as shown in the screen shot below

![image](https://user-images.githubusercontent.com/11155105/39755474-a77c43ec-52ce-11e8-9205-cf600fee08c5.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha please note that the spelling issue still exists in the preview of the courses as in the attached 
![capture](https://user-images.githubusercontent.com/37042927/39965060-36671048-5692-11e8-91a3-01ed8781e795.PNG)
