### ISSUE TITLE
Consulting Services Form

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#145]
**URL:** http://skillsbuilderpro.com/Services/consulting_services
**Path:** Services > Consulting Services
**Subject:**
-  [ ] Consulting Services page must contain a form.
 
![image](https://user-images.githubusercontent.com/11155105/39406202-580286ec-4bbb-11e8-8cd4-57e3b93239d1.png)

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This issue is a change request, as agreed we are will not implement any new features or enhancements until done with main bugs.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please close for now.

**Comment by Ali-Galal** [comment]
@LamiaSalah kindly remove this menu from the menu structure
@HeshamHassan Add it to the enhancement file
