### ISSUE TITLE
Show Courses in eStore

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#146]
**URL:** http://skillsbuilderpro.com/public/estore/
**Subject:** 
-	I logged on eStore as admin
-	Go through: Catalog> Categories>
-	Deactivate all categories except “Software”
-	Renamed “Software” category to “Courses”
-	The eStore homepage now has one menu item: “Courses” and I cannot connect it with the courses items

 

- [x] How to insert courses under “Courses” menu.
- [x] How to modify the banner to be clickable (open the course when click on it).
- [x] How to modify the Featured section
- [x] The footer needs to be updated like the skillsbuilderpro.com
![image](https://user-images.githubusercontent.com/11155105/39467022-93b96a00-4d34-11e8-8575-fd73f5bbb20f.png)

**Comment by HeshamHassan** [comment]
@ahmedelbougha  

Reminder...

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
This is not a coding issue, it's a matter of 1 hour training, so please consider a free time to do this.
I suggest 4:00 PM today

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Ready but at 4:00pm KSA or 4:00pm CLT?

**Comment by ahmedelbougha** [comment]
@HeshamHassan as agreed:
The first and third issue are fixed.

How to modify the banner to be clickable (open the course when click on it). - I will check @Ali-Galal En Shaa Allah.

The footer issue, we will fix it by 16/05/2018

**Comment by Ali-Galal** [comment]
@ahmedelbougha is today ok with you to meet?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Let's have a meeting tomorrow by 2:00 PM Riyadh time En Shaa Allah

**Comment by Ali-Galal** [comment]
https://global.gotomeeting.com/join/578768597

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
As agreed we will remove Banner slider, and footer slider of Manufacturers.
Another ticket will be created to do allow you making buy from eStore and reflect status on SkillsBuilder .

**Comment by ahmedelbougha** [comment]
24/05/2018

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/26/slideshow-and-carousel-modules-dont/diff

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/26/slideshow-and-carousel-modules-dont/diff

**Comment by ahmedelbougha** [comment]
@Ali-Galal would you please check to close?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please confirm.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we don't know yet how to assign a particular product as a featured one

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
From Admin > Extensions > modules > "Featured > Home Page"
But anyway, we make this done automatically as you create or update any course resource, so you don't need to do it manually.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Would you please confirm and close?

**Comment by HeshamHassan** [comment]
Done

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Why did you re-open this ticket? Would you please mention the reason here.

**Comment by ahmedelbougha** [comment]
As agreed, only resources (trainer and student guide is to be shown here) as feature products.
