### ISSUE TITLE
Take This Course

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#147]
**URL:** http://skillsbuilderpro.com/courses/more/3
**Path:** User11 Login > Learning Paths> Workplace Skills Builder> Managing Projects: First Steps First> More> Course Outlines> Take This Course> 
**Subject:** 
Take this course button leads to Course Calendar. I have to click on one of the active published courses in the calendar list to redirect me to the eStore to complete my payment.

- [x] The calendar items is not clickable.

![image](https://user-images.githubusercontent.com/11155105/39467687-057c57c6-4d38-11e8-8015-ce2c54c2ae53.png)

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please use http://skillsbuilderpro.com/courses/calendar as template for this tab.

**Comment by ahmedelbougha** [comment]
06/05/2018

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/11/issue-sbp147-take-this-course/diff

**Comment by Ali-Galal** [comment]
update?

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @HeshamHassan 
Confirmation please?
This issue is closed but @LamiaSalah said that Hesham told here the issue still persisting.

**Comment by HeshamHassan** [comment]
Done
