### ISSUE TITLE
Links to each Learning path

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#148]
Each learning path link has the name 'courses' and followed by a number. Could you please change the link with each relevant path to add it to internal pages?

**Comment by Ali-Galal** [comment]
@ahmedelbougha Your attention please, this issue has been opened since 4 days

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah 
Currently, category pages are landing pages special to categories (learning paths) and not CMS pages i.e. their hyperlinks are not customized like CMS pages.
Please let me know what do you need and I can let you know if it's applicable or not.

**Comment by Ali-Galal** [comment]
@ahmedelbougha we need to change the link from http://skillsbuilderpro.com/categories/ **courses/1**
to http://skillsbuilderpro.com/categories/ **Small-Business-Builder**

@LamiaSalah confirm

**Comment by LamiaSalah** [comment]
@Ali-Galal Confirmed

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @LamiaSalah 
We are checking the best way to do this, we will put our suggestions and estimation today En Shaa Allah.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
@Ali-Galal 
We need to add other radio button named `Category` in menu item add/edit page `http://skillsbuilderpro.com/cms/menuitem/edit/71` for example, this to allow dropdown list of Categories.

Also we need to add text field to add URL for category in admin category add/edit page `http://skillsbuilderpro.com/categories/edit/1` for example.


So, admin add the URL for category and use menu item to add them to menu with the URL selected (just  like the same scenario of CMS pages)

estimation: 2.5 days.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
we will finish this Issue on 14/05/2018.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/15/issue-sbp148-links-to-each-learning-path/diff

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
This is a big change I need to review it carefully, though it's finished since some time, but I need to finish reviewing first before this done.

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
Sunday 15th of July

**Comment by ahmedelbougha** [comment]
Done, @LamiaSalah @HeshamHassan please check and confirm.
How to use:
1- Go to Admin > categories > edit category
2- Fill the path of the category in `Path` field like `/my-category-path`
3- Go to Admin > CMS > Menu Items 
4- Click `Edit` in front of the category menu item and 
5- In `Menu Item Type` select `Category`
6- Select the category from dropdown list
7- Save
Example of the above check `Small Business Builder` category I changed its path to `/small-business-builder`

**Comment by ahmedelbougha** [comment]
@HeshamHassan , @LamiaSalah 
Confirm please !!

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
