### ISSUE TITLE
Duration Outline 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#149]
The duration needs to be for each unit please instead of having a duration for each title under the unit as in the attached
![capture](https://user-images.githubusercontent.com/37042927/39696349-c3e9600a-51ed-11e8-93e0-6cd8fbcc98ae.PNG)

**Comment by LamiaSalah** [comment]
@ahmedelbougha please note we need this urgently asap

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah 
This is an enhancement of already running functionality, I will put estimation to finish this and let your En Shaa Allah.

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/13/duration-outline/diff

**Comment by LamiaSalah** [comment]
@ahmedelbougha Updates??

**Comment by badr4php** [comment]
@here Merged

**Comment by Ali-Galal** [comment]
@ahmedelbougha we need the following:

- [x] activate all outlines

- [x] the default status for the outline should be active when the admin creates it.

**Comment by badr4php** [comment]
@ahmedelbougha Please advise

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
I will close this issue and reopen new issue for this since they are different issues.

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @HeshamHassan 
Confirmation please?
This issue is closed but @LamiaSalah said that Hesham told here the issue still persisting.

**Comment by HeshamHassan** [comment]
Done
