### ISSUE TITLE
Contact Us Page 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#150]
Please add Egypt Address in the contact us page as follows:

P.O Box 23,New Cairo, 11477
Tel: +2 02 23094632
email: info@skillsbuilderpro.com

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Would you please send the position on Google Maps?

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha 
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/14/issue-150-contact-us-page-new-address/diff

**Comment by ahmedelbougha** [comment]
merged
