### ISSUE TITLE
eStore Name

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#151]
Replace the estore name at all locations to that letter format: **eStore**

**Comment by mahmoud-hussien1** [comment]
14/05/2018

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/16/issue-151-change-estore-word-to-estore/diff

**Comment by badr4php** [comment]
@here Merged

**Comment by Ali-Galal** [comment]
Still exist

**Comment by Ali-Galal** [comment]
![2](https://user-images.githubusercontent.com/36264944/40277568-8eba9c82-5c29-11e8-8443-0601802f309a.PNG)
![1](https://user-images.githubusercontent.com/36264944/40277569-8edc84a0-5c29-11e8-9ea4-76fc5add8e60.PNG)

**Comment by badr4php** [comment]
@Ali-Galal  This is menu item you can change it  in admin  here http://skillsbuilderpro.com/cms/menuitem
![40277569-8edc84a0-5c29-11e8-9ea4-76fc5add8e60](https://user-images.githubusercontent.com/24792169/40303355-b1411442-5cf2-11e8-88b0-e0312ecc47c0.PNG)
