### ISSUE TITLE
Delete from footer 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#152]
@ahmedelbougha Please delete Consulting Services and How can SBP help you from the footer

**Comment by Ali-Galal** [comment]
@ahmedelbougha kindly inform me with the path of the footer page to edit it by myself

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal 
path to footer: /themes/skillsbuilder/layout/footer_front.phtml

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @HeshamHassan 
Confirmation please?
This issue is closed but @LamiaSalah said that Hesham told here the issue still persisting.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
The issue still available:
![image](https://user-images.githubusercontent.com/11155105/41843697-debef674-7876-11e8-858a-c9924a6196e4.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha,  yes, this needs to be deleted

**Comment by Ali-Galal** [comment]
@ahmedelbougha @LamiaSalah I will remove it after the delivery of the project
