### ISSUE TITLE
The White Gab between Banner and the Section Next to It

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#153]
**URL:** http://skillsbuilderpro.com/
**Subject:** There is a white space   between the banner picture and the 4 icons in the below section.   Remove this space or adjust   the banner pictures size.
![image](https://user-images.githubusercontent.com/11155105/40027309-1e588cec-57e2-11e8-8b95-e0c861114bc4.png)

![image](https://user-images.githubusercontent.com/11155105/40027312-2140c9e2-57e2-11e8-8a9d-eb499e2cfe1a.png)

![image](https://user-images.githubusercontent.com/11155105/40027318-275f1a7c-57e2-11e8-85df-3986587b74e2.png)

![image](https://user-images.githubusercontent.com/11155105/40027322-2b7e2d5a-57e2-11e8-94b6-48dd3965b583.png)

**Comment by Ali-Galal** [comment]
@ahmedelbougha I think the issue with image size (we need to unify it)

**Comment by badr4php** [comment]
Merged

**Comment by Ali-Galal** [comment]
The issue still exist as before

**Comment by badr4php** [comment]
@here Merged
