### ISSUE TITLE
The new theme is not clear

### ISSUE THREAD

**Issue by mahmoud-hussien1** [camelcasetechsd/skillsbuilder#154]
we can't navigate into the theme and the screenshots on the site page are small, so can you send me template source code if available please? @Ali-Galal 
http://www.dreamtemplate.com/templates/9363/university-degree-site-template.html

**Comment by Ali-Galal** [comment]
I didn't purchase it yet, I need the confirmation from your side that It could be implemented in KWP website to proceed its payment

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check this for live preview of the theme: http://www.dreamtemplate.com/preview/?url=http://www.htmlpreviews.com/cloud/university/strophy6/

**Comment by ahmedelbougha** [comment]
@LamiaSalah @Ali-Galal 
We need to close SkillsBuilder first before starting new theming project.

**Comment by Ali-Galal** [comment]
@ahmedelbougha I didn't get it, kindly explain

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please go ahead purchase it.
