### ISSUE TITLE
The space between 4 squares and footer

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#155]
![capture](https://user-images.githubusercontent.com/36264944/40306091-fb902cdc-5d05-11e8-9f1b-a385a8a6c59a.PNG)

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal just wait page to load please.

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
It seems the problem is not related to page loading, I found that div has a fixed height 740px.
Please check again.

**Comment by ahmedelbougha** [comment]
23/05/2018

**Comment by mahmoud-hussien1** [comment]
PR  - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/29/issue-155-set-div-height-with-element/diff

**Comment by ahmedelbougha** [comment]
done
@Ali-Galal 
Please check to close

**Comment by ahmedelbougha** [comment]
closed due to inactivity
