### ISSUE TITLE
The HTML code appeared to the user in brief for learning paths

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#157]
![capture](https://user-images.githubusercontent.com/36264944/40306247-9c718d44-5d06-11e8-97a2-3d331980c98c.PNG)

**Comment by badr4php** [comment]
@here Merged

**Comment by Ali-Galal** [comment]
solved only in the screenshot's place, still exist in other places, the screenshot is just an example

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal as I saw, it's solved in learning path page. please tell me where i find problem.

**Comment by Ali-Galal** [comment]
in the **learning path>Small Business Builder** 
in the **Crowdsourcing for Quick Results** brief 

but this also just another example

**Comment by badr4php** [comment]
@here Merged
