### ISSUE TITLE
Learning Paths link

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#158]
@ahmedelbougha this issue has been raised before and I'm not sure if it's closed. The link for each learning path should have its name and not with numbers ( http://skillsbuilderpro.com/categories/courses/1)

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
are we done with this? if so please update the ticket with PR.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/15/issue-sbp148-links-to-each-learning-path/diff

**Comment by ahmedelbougha** [comment]
@LamiaSalah this is a duplicate for #148 , I'm closing this to avoid confusion.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Now we have a duplicated issue: #148 or #158. Which one you have to close, because you closed both of them?!

**Comment by ahmedelbougha** [comment]
@HeshamHassan as said in the comment above I'm closing (this) which means I'm closing #158, it's already closed.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Then we will continue with #148 for now
