### ISSUE TITLE
Activate Outlines

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/skillsbuilder#159]
@Ali-Galal  
Activate all outlines
The default status for the outline should be active when the admin creates it.

Estimated: 3 hours.
Date: 23/05/2018

**Comment by badr4php** [comment]
@ahmedelbougha  PR : https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/27/enhancment-sbp-159-activate-outlines/diff

**Comment by ahmedelbougha** [comment]
done
@Ali-Galal please check to close

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
