### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#160]
@ahmedelbougha please edit the spelling of the word 'Required' in Contact Us page

**Comment by ahmedelbougha** [comment]
31/05/2018

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/30/issue-118-spelling-mistake/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Issue fixed, please confirm.

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
