### ISSUE TITLE
pending issues

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#161]
@ahmedelbougha please note the below issues that need fixing:

Homepage:
1) The more details button under Why Skills Builder Pro, can we delete it and reduce the space?
2) The panel under the banner where the four buttons are: Trainr’s is misspelled. It should be' Trainer’s'

Courses
1) Remove 'We are currently full from all courses

Training:
1) Please remove the link from Training, it's a root that shouldn't be linked to a page

Contact Us:
1) Please change the order of the address to be: Riyadh, Cairo and then USA.
2) For USA address, please make it 7610 W Hwy 71, Suite F, Austin TX,78735 
3) Please change the text on the bottom to 'Submit'

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and update with expected date of delivery.

**Comment by mahmoud-hussien1** [comment]
estimated date: Sunday 03/06/2018.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah please tell me the URL to training page and the link you need us to remove it.

**Comment by LamiaSalah** [comment]
http://skillsbuilderpro.com/resource_not_found 

we need to remove, it doesn't need to link to any page

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah this page means you have not access to target page.
so, if there is link found in any page and redirect you to this URL, please tell me.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1 could you please call me as I'm not sure I understand what you mean?

**Comment by mahmoud-hussien1** [comment]
please call @ahmedelbougha.

**Comment by ahmedelbougha** [comment]
@LamiaSalah the issue of Training menu item issue has been resolved, it can be fixed from CMS admin, please check this: http://skillsbuilderpro.com/cms/menuitem/edit/53

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/31/issue-161-pending-issues/diff

**Comment by ahmedelbougha** [comment]
merged.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Issues fixed, would you please check and confirm?

**Comment by LamiaSalah** [comment]
@ahmedelbougha  confirmed

**Comment by LamiaSalah** [comment]
@ahmedelbougha  Confirmed. But please note that the address in the US map has not changed

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Would you please check and change the map address?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/32/issue-161-change-address-for-usa/diff

**Comment by ahmedelbougha** [comment]
merged, @LamiaSalah please confirm

**Comment by LamiaSalah** [comment]
Confirmed
