### ISSUE TITLE
Course Resources Purchasing Error

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#162]
**URL:** http://skillsbuilderpro.com/something_went_wrong
**Path:** Learning Path> Small Business Builder> Building a Consulting Business> More> Course Resources> Purchase now
**Subject:** 
Cannot purchase from SkillsBuilderPro.com
![image](https://user-images.githubusercontent.com/11155105/42133032-aa024f30-7d2b-11e8-9409-659d8c5d0dbb.png)

**Comment by Ali-Galal** [comment]
@ahmedelbougha give this a high priority for this issue as we need to finalize the project as you know

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
@HeshamHassan I think you mentioned this was fixed in another ticket correct?

**Comment by ahmedelbougha** [comment]
https://github.com/camelcasetechsd/skillsbuilder/issues/91#issuecomment-403291714

**Comment by HeshamHassan** [comment]
Done
