### ISSUE TITLE
Instructor Materials Appear in Hushes

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#163]
**URL:** http://skillsbuilderpro.com/courses/training-materials#
**Path:** User Menu> Instructor> Instructor resources> Training Materials
**Subject:** 
Instructor materials appear in hushes.
![image](https://user-images.githubusercontent.com/11155105/42149063-4c5e1d66-7ddd-11e8-86f2-78d40343cc90.png)

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and fix.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/47/issue-163-instructor-material-appear-in/diff

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
Done.
