### ISSUE TITLE
Instructor General Resources: Not Found

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#164]
**URL:** http://skillsbuilderpro.com/resource_not_found
**Path:** User Menu> Instructor> Instructor resources> General Resources
**Subject:** 
Instructor General Resources: Not Found
![image](https://user-images.githubusercontent.com/11155105/42149223-ff45b6d2-7ddd-11e8-986e-9e4489441c2e.png)

**Comment by ahmedelbougha** [comment]
we will create script to copy courses and resources from skillesbuilder to estore as products En Shaa Allah.

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please check and fix.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan @ahmedelbougha 
it's because of inactivation of the CMS page.
i activate it and it works now.

**Comment by ahmedelbougha** [comment]
Thanks @mahmoud-hussien1 
@HeshamHassan would you please check and confirm?

**Comment by HeshamHassan** [comment]
Done
