### ISSUE TITLE
Homepage Banner Links

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#165]
•	The second banner in the carousel is: Learn the skills you need. It currently links to Career Skills Builder. Please link it to Workplace Skills Builder. http://skillsbuilderpro.com/categories/courses/5
•	The fourth banner in the carousel is: Enrich your portfolio. add the text: Partner with SBP above “Enrich Your Portfolio''

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/37/issue-165-comments-in-issue-done/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by LamiaSalah** [comment]
@ahmedelbougha the links are still the same

**Comment by ahmedelbougha** [comment]
@LamiaSalah check again please

**Comment by LamiaSalah** [comment]
@ahmedelbougha Confirmed
