### ISSUE TITLE
Reserve Page

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#168]
http://skillsbuilderpro.com/quote?type=Private

Please fix the tabs view at the top(Public Training) and (Private Training)
Remove all Hijri dates from the website.

**Comment by mahmoud-hussien1** [comment]
PR  - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/38/issue-168-reserve-page/diff

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Merged.
@mahmoud-hussien1 
Please fix the width of the page.

**Comment by LamiaSalah** [comment]
@ahmedelbougha Hijri dates are still available

**Comment by ahmedelbougha** [comment]
@LamiaSalah ok, @mahmoud-hussien1 please take care of this.

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/45/issue-168-notes-on-reserve-page/diff

**Comment by ahmedelbougha** [comment]
done

**Comment by ahmedelbougha** [comment]
@LamiaSalah please confirm

**Comment by LamiaSalah** [comment]
Confirmed
