### ISSUE TITLE
Contact Us Page

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#169]
Can we move the feedback form to the top of the page above the addresses?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/39/move-feedback-form-to-top-op-page/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by LamiaSalah** [comment]
@ahmedelbougha the form is still at the bottom of the page

**Comment by ahmedelbougha** [comment]
@LamiaSalah check again please

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
