### ISSUE TITLE
Links for Social Media 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#170]
On all courses, the three social media tabs at the bottom should link to 
- www.facebook.com/skillsbuilderpro 
-https://twitter.com/SBP_2016?lang=en
- https://www.linkedin.com/company/skillsbuilderpro/

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/40/change-social-media-links/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@LamiaSalah please confirm to close

**Comment by LamiaSalah** [comment]
@ahmedelbougha please use the above links, I edited them. Sorry for the inconvenience.

**Comment by ahmedelbougha** [comment]
@LamiaSalah there's no changes in the links, they are all the same.

**Comment by LamiaSalah** [comment]
@ahmedelbougha  links updated

**Comment by ahmedelbougha** [comment]
Sunday 15/07/2018

**Comment by ahmedelbougha** [comment]
done

**Comment by LamiaSalah** [comment]
@ahmedelbougha confirmed
