### ISSUE TITLE
Courses Duration

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#171]

**Comment by LamiaSalah** [comment]
@ahmedelbougha  could you please hide the duration of the course added in all courses for now?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/41/issue-171-hide-duration-from-course-more/diff

**Comment by ahmedelbougha** [comment]
merged

**Comment by ahmedelbougha** [comment]
@LamiaSalah please confirm to close

**Comment by LamiaSalah** [comment]
The units duration is the one needed to be hidden , not this one please

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise what is done about this!

**Comment by ahmedelbougha** [comment]
Sunday: 15/07/2018

**Comment by ahmedelbougha** [comment]
done

**Comment by LamiaSalah** [comment]
Confirmed
