### ISSUE TITLE
New ATP

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#172]
We need to have separate registration forms for each user. ATP, Trainer and Students. 
[Website Application Form -Trainers.docx](https://github.com/camelcasetechsd/skillsbuilder/files/2173617/Website.Application.Form.-Trainers.docx)
[Website Application Form-ATP.docx](https://github.com/camelcasetechsd/skillsbuilder/files/2173619/Website.Application.Form-ATP.docx)

**Comment by ahmedelbougha** [comment]
Estimation of needed work, I'll let you know about it today En Shaa Allah

**Comment by ahmedelbougha** [comment]
@Ali-Galal and @LamiaSalah 
I have sent both of you and email with files commented.

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise the status of this request

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
I sent you an email with the estimated time, you didn't reply me with approval until now. Do you want us to go ahead with this?

**Comment by LamiaSalah** [comment]
@ahmedelbougha I haven't got anything. Yes, you can start immediately. Ho long would this take, please?

**Comment by ahmedelbougha** [comment]
@LamiaSalah time estimation is 6.5 days, please check for email subject `Status Update`

**Comment by LamiaSalah** [comment]
@ahmedelbougha thanks

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
Issue in progress.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check with @Ali-Galal

**Comment by LamiaSalah** [comment]
@ahmedelbougha This is to confirm that the forms that will be added are:
- Trainers Form
- ATP
- Student 

We don't need a form for RESELLERS. 
I'll send you the student's form shortly

**Comment by LamiaSalah** [comment]
[Student Registration Form.docx](https://github.com/camelcasetechsd/skillsbuilder/files/2269263/Student.Registration.Form.docx)

@ahmedelbougha attached is the registration form for students

**Comment by LamiaSalah** [comment]
@ahmedelbougha the delivery date for this was supposed to be 20 days ago as per your advise in the thread above!!

**Comment by ahmedelbougha** [comment]
ATP: 
        user: http://skillsbuilderpro.com/atp/register
        organization: http://skillsbuilderpro.com/front/organizations/new/2

Student: http://skillsbuilderpro.com/student/register
Trainer: http://skillsbuilderpro.com/trainer/register

**Comment by LamiaSalah** [comment]
@ahmedelbougha please find below feedback about the above forms:

New User Form:

- [x]	Change title to  ‘ New Organization’s Admin’
- [x]	Delete Space at the top, too much spacing
- [ ]	Make Titles: Admin First name, etc….
- [x]	Make Security Answers all in one line.

Student Form:

- [ ]	City must not be textbox. It must be DDM that filtered with the cities related to the chosen country.
@ahmedelbougha **there is no feature with this in site so please advise.**
- [x]	Work Status: The radio button needs to be centered with its caption.
- [x]	Work Experience: The radio button needs to be centered with its caption.
- [x]	This form needs a privacy Police and its agree checkbox (done).
- [x]	This form needs a captcha (done).


Trainer’s Form: 

- [x]	Change Title to ‘ New Trainer’s Registration Form’ 
- [x]	Change Educations title to ‘Training Background’
- [x]	When removing “Added education”, the rest of educations number still static without auto-numbering.
- [x]	Fix all format under this section 
- [x]	Please remove duplicated titles inside all fields.
- [x]	When removing “Added Certification”, the rest of Certifications number still static without auto numbering.
- [x]	Area of expertise: The required was DDM. The application is checkboxes.
- [x]	Language: Please add the note in the form next to this title.
- [x]	The appearance is not good. It must be smaller and acceptable.
- [x]	When removing “Added language”, the rest of languages number still static without autonumbering.
- [x]	“My Language” field caption must be “Please specify”
- [x]	Duplicated title. 
- [x]	Please fix the format.
- [x]	Learning Paths: Please add the note in the form next to this title.
- [x]	The rating section is put in wrong way, please add as in the form provided.
- [x]	Resume: Please add the text: Please attach your CV
- [x]	Video section: Please add the note in the form next to this title.
- [x]	Make Security Answers all in one line.
- [x]	The application is prepared for instructor. The role and agreement provided in the application is Training manager.
- [x]	Also the application is prepared for instructor, so the application must not have a role choice checkbox.


For New Organization Form:

Kindly apply the same fields provided in our form so I can review and send you feedback.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah , @HeshamHassan 
We are done with the forms and most of your comments (except two of them) also, styling is finished, right now we are doing enhancements for the validation styling and other stuff to make the forms look better.
You can look on latest changes on production for the time being.

**Comment by LamiaSalah** [comment]
@ahmedelbougha thanks Ahmed, this looks much better. Kindly advise when this is completed to have a final review.

**Comment by ahmedelbougha** [comment]
@LamiaSalah, @HeshamHassan , @Ali-Galal 
It's completed, please check and let me know your feedback

**Comment by LamiaSalah** [comment]
Dear Ahmed,

I’ll reply here as there are lots of details. The info added for the two forms (ATP and Trainer) have lots of variations from the documents I sent you.

Organization


-          The sections are different from those in the doc provided, they should only be two main sections:

Part 1: Business Account Profile
Part 2: ATP Partner Qualifications and Business Plan


-          The content under each section is different from the info in the doc. Please add exactly the wording in the sheet.

-          The map is not available

-          Can we have it divided into sections like the Trainer’s one? It’s very long this way.


Trainers



User Profile:

-          Countries are not added in alphabetical order

-          Phone number should be added after the country not before (also in alphabetical order)

-          The linkedin field should be in the user profile section not the Training background.


Training Background

-          Education and Certifications should be with capital letters.

-          Professional Certifications is not like the doc.

-          Put the selection field for languages next to the text (Native, Fluent, Conversational) and not above it.



Work

-          Why is it called this way?

-          Please change it to Work Experience

-          Add the text EXACTLY like the doc for all fields.



Finish

-          I can’t see what is in this section.


Could you please apply the above changes and update us at the soonest?

Regards,

lamiaa

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha @LamiaSalah  
In Progress.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Kindly update me with the forms URLs

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise when this will be in place?

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah fixed, please check.

**Comment by Ali-Galal** [comment]
Could you please send the URLs

**Comment by LamiaSalah** [comment]
@ahmedelbougha for the Trainers Form:

**User profile:**
The country code filed should have the Country before the code and added in Alphabetical order 
**Training Background:**
- In Professional Certifications section the form is not like the one we provided and missing fields. 
**Work Experience**
- Please add the same text as requested:  SBP Learning Paths you want to teach. Click all that apply.
- The last three fields do not have the same text in our request, please amend it. 

For the Organization Form
**Part 2: Business Background**
- Add countries in Alphabetical order 
- In history of work and competitive advantage add number of words for each field
- Other Annual revenue: Please add it as it is in the form we sent
- For Customer Rating: add it as it is
- Professional Training Locations: add Full text

**Business Plan tab**
- Add full text and fields, the full section is completely different from the one in our form 

In all teh forms, the field titile need to be added propely in one or 2 lines maximum

**Comment by LamiaSalah** [comment]
Dear Ahmed,

I went through the forms and checked the edits. There are still lots of variations between the forms and what we requested. Especially the text for each field.

Also the format need to be fixed as the titles for the fields are added in many lines.

I added my comments on Github. Please advise when these edits will be finalized.

Regards,

Lamiaa

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
_Student Form_:
![image](https://user-images.githubusercontent.com/11155105/46913519-2609fc00-cf97-11e8-975e-48365ab112cf.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
_Instructor Form_: 
![image](https://user-images.githubusercontent.com/11155105/46913556-01faea80-cf98-11e8-86e9-db1ecda9f0b8.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
_New Organization’s Admin_:
![image](https://user-images.githubusercontent.com/11155105/46913589-e9d79b00-cf98-11e8-8b24-264abd18500c.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
_New Organization Form_:
![image](https://user-images.githubusercontent.com/11155105/46913661-5a32ec00-cf9a-11e8-8ec9-b19bfb35c768.png)

**Comment by HeshamHassan** [comment]
**Trainer Form:**
The form cannot be submitted: 
- [x] Resume is not accepted to be uploaded.
- [ ] Resume field needs a note explains the supported file types.
![image](https://user-images.githubusercontent.com/11155105/47265995-c6809300-d538-11e8-8f69-bcbeb4045082.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Captcha keeps the previous values and shows them on mouse click. Kindly stop that for this field.
![image](https://user-images.githubusercontent.com/11155105/47266493-1e6ec800-d540-11e8-891b-94549d1f5384.png)

**Comment by HeshamHassan** [comment]
Student Form is done.

**Comment by HeshamHassan** [comment]
Instructor Form is done.

**Comment by HeshamHassan** [comment]
TM Form is done.

**Comment by HeshamHassan** [comment]
Organization Form is done.
