### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#173]
**Subject:**
The following links are leading to empty pages:
- [ ] Footer> Services> Skills GAP Analysis
- [ ] Footer> eStore> Membership
- [ ] Footer> eStore> Bookink
![image](https://user-images.githubusercontent.com/11155105/42417547-e431e48a-8295-11e8-91ad-ca2ac5bb59f9.png)

**Comment by ahmedelbougha** [comment]
- Footer> Services> Skills GAP Analysis: it was disabled and we re-activated it
- eStore> Membership: please don't start any links paths with **/estore** as it's reserved for eStore pages
- eStore> Bookink: please don't start any links paths with **/estore** as it's reserved for eStore pages

**Comment by HeshamHassan** [comment]
@Ali-Galal 
Kindly advice

**Comment by Ali-Galal** [comment]
@LamiaSalah Kindly edit the URLs

**Comment by LamiaSalah** [comment]
@Ali-Galal I'm not sure what links that need to be edited

**Comment by LamiaSalah** [comment]
@Ali-Galal we just need to delete how can SBP help you

**Comment by Ali-Galal** [comment]
Regarding the issue @ahmedelbougha we don't know how to edit the links paths, kindly advise 

Regarding "delete how can SBP help you"
@LamiaSalah I will do it after the delivery it will not take time
@HeshamHassan kindly add it to my tasks

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
The change of paths can be done through CMS

**Comment by Ali-Galal** [comment]
@ahmedelbougha How?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Please don't worry, all pages are working now.

**Comment by ahmedelbougha** [comment]
@HeshamHassan @LamiaSalah 
Confirm and close please.

**Comment by HeshamHassan** [comment]
Done
