### ISSUE TITLE
Trainer and Student Guides

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#174]
@ahmedelbougha we need to have the current Trainers and Student's Guides titles highlighted as English from the drop-down in the resources section, and others to be highlighted as Arabic, upon adding the Arabic resources, they will be having the same names.

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Please put more elaborating description, I cannot understand where to do the above and when to do it.

**Comment by LamiaSalah** [comment]
@ahmedelbougha no problem, can discuss this later as it's related to the Arabic section. Won't be delivered in this phase.

**Comment by Ali-Galal** [comment]
@ahmedelbougha when we adding the trainer guide or student guide, we need to differentiate between EN and AR version

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @LamiaSalah 
Whenever you add/edit any resource, you can upload 2 versions English and Arabic.
![sbp-tg-sg](https://user-images.githubusercontent.com/8982139/42844404-17942354-8a13-11e8-970a-f2ebce070080.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha in the estore, there's no option in the drop-down for Arabic Trainer or Student Guides

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by LamiaSalah** [comment]
@ahmedelbougha as agreed yesterday you were supposed to send us a demo for this

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

(( related to #213 ))

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
> ![image](https://user-images.githubusercontent.com/11155105/48690817-21151980-ebe1-11e8-99b9-71306815ef07.png)
The above process -you sent- is not the current one to add the arabic recourses.
Kindly update me with the right process.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by LamiaSalah** [comment]
@HeshamHassan  this has been finished. Will close the issue
