### ISSUE TITLE
After Reviewing the Scope

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#175]
### Phase 2
2.1 Registration modifications:
- [x] Disabling testing center administrator and testing center proctor roles.
	_These roles appear in the user profile when S.Admin open._
- [x] For instructor role, allow user to add video link, upload bio file(doc,pdf,ppt) and writing a bio in wysiwyg enabled text area.
	_There is no option to allow the instructor to upload files._

2.2 Course and course events modifications:
- [x] Change course type to audible (link to amazon product)
	_Audible resource is not available to the users._

2.3 Course calendar:
- [x] Training provider course calendar 
	_The training provider user can create, but cannot view his events calendar._

2.4 eStore modifications:
Each course may have 1 to 5 products creation which are:
- [x] Audible(link to amazon product. It’s not allowed to be bought from eStore) 
	_User cannot access this type._

### Phase 3
3.1 Home page structure:
- [x] Coming soon
	_It is not available._

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check with @Ali-Galal

**Comment by ahmedelbougha** [comment]
@HeshamHassan please confirm and close, as agreed with @LamiaSalah  she don't need the Coming Soon section.

**Comment by HeshamHassan** [comment]
As per **@LamiaSalah** confirmation,
The "Coming Soon Section" point will be postponed for now.

**Comment by Ali-Galal** [comment]
@HeshamHassan create a new issue for coming soon and label it as postponed
