### ISSUE TITLE
Enroll to Course

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#176]
**URL:** http://skillsbuilderpro.com/courses/more/8
**Path:** Learning Paths> Small Business Builder> Course Outlines> Take This Course> Enroll
**Subject:**
Error message appears when click on “Enroll”. This error appears with all roles even Admin.

![image](https://user-images.githubusercontent.com/11155105/43070047-647d653c-8e77-11e8-9b17-5d548832e1a5.png)

![image](https://user-images.githubusercontent.com/11155105/43070051-6814d8d8-8e77-11e8-84ee-9d1ad5f06f8e.png)

**Comment by ahmedelbougha** [comment]
done
@HeshamHassan 
Check and confirm.

**Comment by HeshamHassan** [comment]
Done
