### ISSUE TITLE
Course Event has No Price

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#177]
**URL:** http://skillsbuilderpro.com/estore/index.php?route=checkout/cart
**Path:** Learning Paths> Small Business Builder> Course Outlines> Take This Course> Enroll
**Subject:**
Course event has no price.
- [ ] How to create “Course Event Price”?

![image](https://user-images.githubusercontent.com/11155105/43132045-43ac7a42-8f43-11e8-88b6-efd5c834d03e.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
You have to fill course price in SkillsBuilder itself, it will update the eStore automatically.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Where to fill that price?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Go to any course edit page: example http://skillsbuilderpro.com/courses/edit/34
You can find Price field there.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Any update????????????

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Each course has its recommended price. 
While creating an event, The ATP will modify the course recommended price so the modified price will affect only the current created event.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
No, that wasn't the requirement, please return to Ali to let you know about this.

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly advice!
