### ISSUE TITLE
Training Manager Event List

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#178]
**Subject:**
Training Manager can create events. But, he cannot view the events list.
- [x] How can TM access his created events (Event List)?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This could be done by CMS! Anyway I have changed this myself, please take care of this in the future.
Now, you can reach that page when you login as TM using Training Manager > Training Calendar

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please confirm and close.

**Comment by HeshamHassan** [comment]
Done.
