### ISSUE TITLE
pdf attachment

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#179]
can we add the option of attaching text to a pdf file?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah , @HeshamHassan 
Not yet, it seems as new requirement, I'm not sure if you have send me details about it?

**Comment by LamiaSalah** [comment]
@ahmedelbougha I need to have the option of linking any text to a pdf file after uploading it to the system

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
will include this as new feature please confirm ?

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah 
kindly need more details about this issue please

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc I need to attached text to be clickable to a pdf file!
Please advise cost first before proceeding.
