### ISSUE TITLE
Access to courses

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#180]
The access to the courses from the learning paths dropdown is not working, it only works from the internal pages.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
i tested this page and it works. if you see other thing, please tell me.
http://skillsbuilderpro.com/categories/courses/8

**Comment by LamiaSalah** [comment]
It's working now.

**Comment by HeshamHassan** [comment]
Sorry, 
It still not working till now.
**Scenario:**
1. Open http://skillsbuilderpro.com/home-default as a guest.
2. click on Learning Path DDM to open
3. click on any learning path in the menu
4. page redirects me to "Log In" page
Also, most roles act the same as "Guest" and cannot access the learning path DDM.

**Comment by ahmedelbougha** [comment]
Fixed

**Comment by HeshamHassan** [comment]
Done.
