### ISSUE TITLE
eStore Log in and Registration 

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#181]
**URL:** http://skillsbuilderpro.com/estore/index.php?route=checkout/checkout
**Path:** SBP Home> eStore> Add to cart> Checkout
**Subject:**
Scenario:
1.	SBP home page “as a guest”.
2.	Click on eStore menu
3.	Add item to the cart
4.	Checkout
![image](https://user-images.githubusercontent.com/11155105/44785748-a1a41b00-ab9a-11e8-9edf-bbe5abc5d99f.png)

 - [ ] New Customer must redirect to the new user registration form at SBP.
 - [x] Returning Customer and reset password must redirect to the login page at SBP.
 - [x] The “Guest Checkout” option is not applicable.

**Comment by ahmedelbougha** [comment]
@Ali-Galal @HeshamHassan 
"Guest checkout" option removed, since it's a setting in the system.
The other 2 options are enhancements, please approve.

**Comment by Ali-Galal** [comment]
@ahmedelbougha 
1- As we agreed only logged in users (student or instructor), can purchase, so it doesn't make sense that the visitor can access eStore.

2- we already paid to fully implement the eStore, which means that the eStore credentials are synced with our portal.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Point 2 Solved.
Still, Point 1...

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed

**Comment by HeshamHassan** [comment]
All points are done.
