### ISSUE TITLE
ATP Page for Registered Trainer Manager

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#183]
**URL:** http://skillsbuilderpro.com/About/Partner_with_SBP/ATP
**Path:** SBP Home> About> Partner with SBP> ATP
**Subject:**
At the end of Authorized Training Partner page, there is a link: “Apply Now” which redirect me to the new registration form. When I login as an TM:
- [x] The link “Apply Now” must not appear. 
Or, at least redirect to the TM profile, not the new registration form.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
this is a static page. there is no option in static pages to do what you want.

**Comment by Ali-Galal** [comment]
@ahmedelbougha it doesn't make sense that the logged in user can access the registration page.

you can redirect any logged in user that trying to access the registration page to its profile page.

**Comment by ahmedelbougha** [comment]
@badr4php 
Please check

**Comment by badr4php** [comment]
@ahmedelbougha  PR :  https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/57/183-when-loged-in-user-try-to-access/diff

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan it's already fixed:
        
          Page can be accessed by unregistred users , but if logged in user it should
          act as:
          1- Admin && TM will be redirected to /users/new
          2- other roles will be be redirected to /no-access
         
Please confirm and close

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
We cannot change _Apply Now_ link as it's written inside CMS pages content which cannot control it, but we can control the user redirection only.

**Comment by Ali-Galal** [comment]
@ahmedelbougha you can redirect any logged in user that trying to access the registration page to its profile page.

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
That means (ANY) role will be redirected to profile page (Other than Admin) OK?

**Comment by Ali-Galal** [comment]
@Ahmedelbougha I got your point I have a question about it before to decide I will call you in this regard

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
What is your point?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
I clicked on _Apply Now_ and redirected to the TM profile. but I couldn't edit.

Kindly help.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done edit profile button appear now! please confirm and close

**Comment by HeshamHassan** [comment]
Not yet !!!

This screenshot is recentle taken: 
![image](https://user-images.githubusercontent.com/11155105/50297175-2fc74880-048d-11e9-9e20-af4af2f70aba.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by mohamedMahdyCc** [comment]
![image](https://user-images.githubusercontent.com/40764593/50587414-8584f300-0e86-11e9-96d5-d208ea746c68.png)
cannot access user profile when login with `user25`

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
As per our conversation, kindly update the contents of the page.

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@HeshamHassan  please advise

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
As agreed and to remind you:
- If the user is registered and logged on, then he must contact us.
- If the user is "new", then he must click on Apply now...

**Comment by LamiaSalah** [comment]
@HeshamHassan  Done
