### ISSUE TITLE
Bugs (Meeting)

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#185]
- [x] take space between radio button and menu item type 
- [x] remove ATC from organizations form 
- [x] in ATP form " I agree to Atp's privacy statement" capitalize 
- [ ] add category description in the learning path page 
- [x] Number of items in cart in eStore need to be displayed

**Comment by ahmedelbougha** [comment]
All fixed except "in ATP form " I agree to Atp's privacy statement" capitalize", which is part of statements, to be deployed within 1 day En Shaa Allah.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please check

**Comment by HeshamHassan** [comment]
1. Done.
2. Done.
3. Done.
4. Not complete:
5. Done.

**4.** Not complete: when opening the learning path from the home page, I can find the category description. but when open the same learning path from the menu, the description is dismissed.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
**Point 4: Category Description.**
When accessing the learning pass from the menu, I cannot find the description.
But when accessing the same learning pass from the home page, the description exists. 
Kindly check the below screenshots:
- From Menu:
![image](https://user-images.githubusercontent.com/11155105/46258188-d3c4d780-c4ce-11e8-9525-ceb40051401e.png)

- From Home Page: 
![image](https://user-images.githubusercontent.com/11155105/46258190-e808d480-c4ce-11e8-8609-230936a43101.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed, confirm and close.

**Comment by HeshamHassan** [comment]
All Done.
