### ISSUE TITLE
Enhancements (Meeting)

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#187]
- [x] rename category to learning path in backend 
- [x] header height to be smaller 
- [x] cut the end of course description in frontend at end of a phrase (dot) after 150 character (at the end to be 5 lines)

**Comment by HeshamHassan** [comment]
- [ ] Ability to **stop,** **pause** and **resume** a purchased course for a particular user.
- [x] **Pre** and **Post** assessment for each course.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha 
Point 2**
The header height is not smaller than before.
I cannot determine any shrunk height.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
this one is done Pre and Post assessment for each course.
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
will include this `Ability to stop, pause and resume a purchased course for a particular user.` as new feature please confirm ?

**Comment by HeshamHassan** [comment]
> * [ ]  Ability to **stop,** **pause** and **resume** a purchased course for a particular user.
> *

- [x] How to do that feature?

**Comment by mohamedMahdyCc** [comment]
> > * [ ]   Ability to **stop,** **pause** and **resume** a purchased course for a particular user.
> 
> * [x]  How to do that feature?
@HeshamHassan 
ok will discuss this with the team and replying you ASAP nchallah

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
waiting for confirm

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan please close this issue and create new issue with title `Ability to stop, pause and resume a purchased course for a particular user`

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly Advice.

**Comment by HeshamHassan** [comment]
As agreed in the meeting between **@mohamedMahdyCc** and **@HeshamHassan** today..
This feature is moved to a new issue. its new number is: #249
