### ISSUE TITLE
New requirements (Meeting)

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#188]
- [x] when click admin menu from frontend open it in new tab 
- [ ] adding countries, regions, pricing per region 
- [ ] admin can change the statements 
- [ ] home page administration from backend to control the content of Home Page 
- [ ] assign user to distributer 
- [ ] distributer can approve and add reseller and ATPs in its region 
- [ ] reseller can approve and add reseller and ATPs in its sub-region 
- [ ] sort and search in course page in admin 
- [x] course outline duration for instructors only in frontend
- [x] course outlines parent to be calculated automatic from children total durations
- [ ] in course event from - to time fields 
- [x] you have to register the users that are booking public/private (they have to be registred in order to make their booking active)
- [ ] certificate of attendance 
- [ ] attendance sheet
- [x] expiration of resources(trainer and student guides) 
- [ ] ATP, Distributer, Reseller, Instructor (docusign) the other roles are statements 
- [ ] add shoping cart in SBP not only estore
- [ ] add taxes, coupon, voucher in estore

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 
i prepare to start with them next week nchallah

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
please i need to split this **to do list** into separate issues to determine the new feature from the bug and enhancement

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 

please recheck this todo list and close this issue , and take the not done to custom new issue please

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan any update ?

**Comment by MuhammedMahdy** [comment]
@HeshamHassan any update ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
I checked the already existing features in the above list. 
We can have a meeting to discuss the unfinished features.

**Comment by mohamedMahdyCc** [comment]
Ok @HeshamHassan
At first we need to creat issues for the remaining things and close this issue

**Comment by HeshamHassan** [comment]
This issue is closed and the un solved points of it had been separated as the following:
- [#258] adding countries, regions, pricing per region 
- [#259] admin can change the statements 
- [#260] home page administration from backend to control the content of Home Page 
- [#261] assign user to distributer 
- [#262] distributer can approve and add reseller and ATPs in its region 
- [#263] reseller can approve and add reseller and ATPs in its sub-region 
- [#264] sort and search in course page in admin 
- [#265] in course event from - to time fields 
- [#266] certificate of attendance 
- [#267 ] attendance sheet
- [#268] ATP, Distributer, Reseller, Instructor (docusign) the other roles are statements 
- [#269] add shoping cart in SBP not only estore
- [#270] add taxes, coupon, voucher in estore
