### ISSUE TITLE
web analytics 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#192]
@ahmedelbougha we'll use the same email for skilled Matrix to create web analytics account.
please advise when this will be in place

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
As we agreed together on the phone last week, this is small issue, and we are waiting until finishing the current issues (forms and statements), if it's priority to you then I can work on it first.

**Comment by LamiaSalah** [comment]
Confirmed
