### ISSUE TITLE
Course Page – Resources Section

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#193]
**URL:** http://skillsbuilderpro.com/categories/courses/
**Subject:**
The resources section in the course pages is not the same.
The 3 contents (Outlines, Trainer Guide, Student Guide) at the below pages are not in the same order as the rest of the same section at the other course pages:
![image](https://user-images.githubusercontent.com/11155105/45264418-dd659d00-b444-11e8-9731-14f71e94a9b2.png)
![image](https://user-images.githubusercontent.com/11155105/45264421-e48cab00-b444-11e8-8e3b-00fa9a9e7ee5.png)
![image](https://user-images.githubusercontent.com/11155105/45264422-e6ef0500-b444-11e8-8a15-4391f1bb0331.png)
![image](https://user-images.githubusercontent.com/11155105/45264423-e9e9f580-b444-11e8-8432-0e8cc4cefeb0.png)
![image](https://user-images.githubusercontent.com/11155105/45264424-ed7d7c80-b444-11e8-86cc-41ae39e3dabb.png)
![image](https://user-images.githubusercontent.com/11155105/45264425-efdfd680-b444-11e8-9b02-f8243fb15c61.png)
![image](https://user-images.githubusercontent.com/11155105/45264426-f2423080-b444-11e8-9438-67a79a53eb5b.png)
![image](https://user-images.githubusercontent.com/11155105/45264427-f4a48a80-b444-11e8-80c7-a616e63e5422.png)
![image](https://user-images.githubusercontent.com/11155105/45264429-f706e480-b444-11e8-835d-568c18f089a8.png)
![image](https://user-images.githubusercontent.com/11155105/45264430-f9693e80-b444-11e8-8e0e-755de808404b.png)

- [ ] Fix the Course Resources table contents order to be (1- Brief PDF, 2-Trainer's Guide, 3-Student’s Guide) to match with the same section of other courses.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/68/issue-193-order-resources-relative-to-type/diff

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
Done
