### ISSUE TITLE
User Profile Saving Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#194]
**Subject:**
When trying to create a new account or modify an existing account, the form refuses to save changes. And there is no error message to indicate the missing data.
**Case1:** I tried to modify user15 to be Instructor. 
**Case2:** I tried to create a new user account.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
The new user profile applied. But the form still denies being saved. And I faced the following issues:
- The available form shows only the student fields. I cannot find the instructor fields for the instriuctor user (_check user14 and user3 profiles_)
- the google map does not appear in the new form.
- When creating a new user with the role "Instructor" I'm trying to update the Instructor profile and I cannot save. The additional fields that requiring to upload Bio, Picture and Video cannot load the attached files.

So, I cannot create a new user or modify Instructor profile.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
It seems there's misunderstanding. Right now we have 3 new forms:
1- Student
2- Instructor (Trainer)
3- Training Manager
The new forms should be reviewed against the new requirements that you sent, but I have the feeling that you are checking old requirements. 
Please check with Ali, as I sent him the URLs for new registration forms.

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Any update from your side?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
- [ ] Cannot modify old user to be an instructor.
- [ ] Cannot create new Instructor user:
![image](https://user-images.githubusercontent.com/11155105/46581473-23148600-ca42-11e8-8daa-a042495407a4.png)

**Comment by ahmedelbougha** [comment]
Fixed, please check and close.

**Comment by HeshamHassan** [comment]
Done.
