### ISSUE TITLE
Organization Information View Page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#195]
**URL:** http://skillsbuilderpro.com/organizations/more/6
**Subject:**
Fix the view of the page. Data is overlapped in the tables.
![image](https://user-images.githubusercontent.com/11155105/45690755-bbb09800-bb5f-11e8-8548-7892af6c0662.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/67/issue-195-fix-li-height-in-organization/diff

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
The issue still as it is. 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
merged and uploaded to production

**Comment by HeshamHassan** [comment]
Done
