### ISSUE TITLE
Private Training Reservation

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#196]
**URL:** http://skillsbuilderpro.com/quote/training/private/4
**Path:** Learning Path> Course> Book a private session> Reserve>
**Subject:**
Reservation is not working. It gives the below message:
![image](https://user-images.githubusercontent.com/11155105/45472016-9aa10f00-b73b-11e8-95a5-ff711bfc8569.png)

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha this problem related to migration.

**Comment by ahmedelbougha** [comment]
done

**Comment by HeshamHassan** [comment]
Done
