### ISSUE TITLE
Filtered Pages By Learning Path Needs To Be Fixed

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#198]
**URL:** http://skillsbuilderpro.com/Management-Pro?page=2
**Subject:** 
When accessing the learning path “Management Pro” page 2, all courses become in the same learning path. The pages transferred from 3 pages to 11 pages.
![image](https://user-images.githubusercontent.com/11155105/45596898-292bbf80-b9cc-11e8-867f-665ede4f4539.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan, @LamiaSalah  
It has been fixed and deployed to production

**Comment by HeshamHassan** [comment]
Done.
