### ISSUE TITLE
SBP-2: Replace the `certigate` database to `skillsbuilder`

### ISSUE THREAD

**Issue by AbdElmoneimMohamed** [camelcasetechsd/skillsbuilder#2]

**Comment by AbdElmoneimMohamed** [comment]
PR
http://git.camelcasetech.com/camelCase/certigate/pulls/2

**Comment by solimansamy** [comment]
https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/commit/fdea2ee5e0145d5be71619c367f6a801463cd386

https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/commit/b187e2eee5c6027a6585e7677375d63fb933e940
