### ISSUE TITLE
Coming soon

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#200]
**Phase** 3
3.1 Homepage structure: **Coming soon** It is not available.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
fixed

**Comment by Ali-Galal** [comment]
@ahmedelbougha This issue instead of issue number 175

**Comment by ahmedelbougha** [comment]
@Ali-Galal , @HeshamHassan 
This is already fixed, why did you label it as postponed?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
OK

**Comment by Ali-Galal** [comment]
@heshamhassan kindly check it and confirm or attach the screenshot

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/46334679-a7739d00-c62d-11e8-8cd8-6438ec9b84df.png)

**Comment by ahmedelbougha** [comment]
No need, as I was confused between this and some other issue.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha @LamiaSalah 
please send to me more details about this issue, what is the required here ?

**Comment by HeshamHassan** [comment]
This feature is present at the project scope. and till now it is not present at real.
Kindly, discuss its details with **@ahmedelbougha**

**Comment by LamiaSalah** [comment]
@HeshamHassan  @mohamedMahdyCc this is not needed at the current stage. will close it for now
