### ISSUE TITLE
Flipping Books to be Re-uploaded

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#201]
**@ahmedelbougha** 
Is there a limitation for the flipping book size? I cannot upload the flipping book because of the .zip file size. I got the message in the below screenshot.
 - [ ] Kindly free up the .zip flipping book size.
![image](https://user-images.githubusercontent.com/11155105/46404710-aa928a00-c70e-11e8-8523-d923f1d8b7b0.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
If I remember it correctly, I think @Ali-Galal increased that size once before from server settings, but we will check on our side if there's additional limitation En Shaa Allah and let you know today.
What is the size of the book you are trying to upload?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Till now... I have one with 300MB!
We may have larger flipping book files.

**@Ali-Galal** 
Kindly advice about the size.

**Comment by Ali-Galal** [comment]
@ahmedelbougha is it applicable to remove the limitation at all?

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
This issue appears to me and my colleagues in Egypt: 
When uploading the flipping book, the status bar count the uploading to 99% then the following page appears: 
![image](https://user-images.githubusercontent.com/11155105/46596231-717a6100-cae4-11e8-9b68-b9580d3015fd.png)

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
This is a server issue, the maximum size of file must be 200 Mb or less, you need to change the server configuration to support hat size of files.

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
Kindly Advice

**Comment by Ali-Galal** [comment]
@HeshamHassan try again please

**Comment by HeshamHassan** [comment]
Done
