### ISSUE TITLE
Evaluation Template Saving Error

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#202]
I tried to modify the evaluation template. the website denied saving the changes. and gives me the following message: 
![image](https://user-images.githubusercontent.com/11155105/46675835-f9955f00-cbe7-11e8-9531-d760ae0e26ed.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
I tried multi ways, I found that the text box does not accept any special characters. except for the question mark in both English and Arabic languages. 
- [ ] Kindly fix it to accept letters, numbers, and special characters.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan Can i ask the opposite question? which characters you don't want the website to accept?

**Comment by HeshamHassan** [comment]
**@mahmoud-hussien1** 
All types of characters are accepted: letters, numbers, and special characters. Also, for any language.
Conceder it as a normal text box.

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/84/issue-202-evaluation-template-saving-error/diff

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan will fixed soon En Shaa Allah.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Fixed

**Comment by HeshamHassan** [comment]
Done.
