### ISSUE TITLE
Courses Format

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#204]
@ahmedelbougha This has been discussed in our meeting but no issue was raised. The text for each course on each learning Path page need to end with a full sentence, as discussed, you need to end the text in the preview page after a full stop.

Also, there are some errors in the preview text as per below:
http://skillsbuilderpro.com/small-business-builder 

**Smart Strategies for Going Global**
With t_oday&rsquo;s_ global economy and the opening of a global marketplace through the Internet, movi..

also in the course Small Business: Management Basics

Today&rsquo;s business environment is a complex place to be, regardless of business size, type, or l...

**Comment by LamiaSalah** [comment]
@ahmedelbougha please note that there are some courses that have the text broken and not complete in the preview display like marketing in the digital world.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc issue ie resolved, but please note there are some courses that have on eor tow words only in the description, like Managing Anger and Coaching and Mentoring your team in Mangement PRo. Just add two or three lines please in full scentences.

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc issue ie resolved, but please note there are some courses that have on eor tow words only in the description, like Managing Anger and Coaching and Mentoring your team in Mangement PRo. Just add two or three lines please in full scentences.

@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed for the text. Please edit the photo of the course **Managing Workplace Conflict** as it's distorted in the learning path Workplace skills Builder
