### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#206]
@ahmedelbougha 

 I need to replace the photos in the preview section for the below courses with the attached photos as they’re distorted. 

Personal Skills Builder http://skillsbuilderpro.com/personal-skills-builder
Power of self-leadership

Career Skills Builder http://skillsbuilderpro.com/Career-Skills-Builder
Public Speaking with confidence

Workplace Skills Builder http://skillsbuilderpro.com/Workplace-Skills-Builder
Workplace Professional 

Management Pro http://skillsbuilderpro.com/Management-Pro
![power of self leadership](https://user-images.githubusercontent.com/37042927/46735480-a4645680-cc96-11e8-95f3-8c38d9a7fb99.jpg)
![workplace professional](https://user-images.githubusercontent.com/37042927/46735502-ab8b6480-cc96-11e8-8537-18b54dd1f518.jpg)
![building high perfromance teams](https://user-images.githubusercontent.com/37042927/46735509-b0e8af00-cc96-11e8-80de-45bbc93d9e34.jpg)
![public speaking with confidence](https://user-images.githubusercontent.com/37042927/46735516-b5ad6300-cc96-11e8-89fe-6483bb97ba2f.jpg)

Building high-performance teams

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
What happens if you upload them?

**Comment by LamiaSalah** [comment]
I can't, this is something I don't have access to, it has to be fixed from your side

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah 
width: 293px.
height: 370px.

**Comment by LamiaSalah** [comment]
Thanks
