### ISSUE TITLE
Training Manager Authorities

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#209]
Training manager must assign the trainer and the trainees/students to the course.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
ok @HeshamHassan will working on this as new feature please confirm ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
waiting for approval

**Comment by HeshamHassan** [comment]
> @HeshamHassan
> waiting for approval

**@Ali-Galal** 
Kindly Advice.

**Comment by HeshamHassan** [comment]
Duplicated Issue #191
