### ISSUE TITLE
SBP-21: [NEW FEATURE] The user will review the generic calendar for specific course from its course page.

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#21]

**Comment by solimansamy** [comment]
We need to add a calendar here http://certigate.camelcasetech.com/courses/more/1/1 likes the one we have here http://certigate.camelcasetech.com/courses/calendar. This calendar should be for the course itself, it will show the course events allover TPs

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/7
