### ISSUE TITLE
Forms Issues

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#210]
- [x] Captcha keeps the previous values.

Captcha keeps the previous values and shows them on mouse click. That issue appears in all forms. Kindly stop that for this field.
![image](https://user-images.githubusercontent.com/11155105/47649600-d595bf80-db8e-11e8-8059-2257d6ed5ff7.png)

- [ ] City fields must be DDM.

The city fields in all forms must be DDM not a free text box.
![image](https://user-images.githubusercontent.com/11155105/47650259-c6b00c80-db90-11e8-8693-66279c157176.png)

- [ ] Uploaded Files properities. 

- All fields that ask for browsing and uploading files in all forms need a hint that describes the type of the needed file and the maximum allowed size.
- Filter browser page with allowed extinction files.

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
please, tell me the maximum size that you want to the files.

**Comment by HeshamHassan** [comment]
**@mahmoud-hussien1** 
I didn't get what you ask for?

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan  i mean what is the maximum size that you want me to assign for uploading files? or make it as the maximum size that server accept.

**Comment by HeshamHassan** [comment]
**@mahmoud-hussien1** 
What is the maximum size that the database can accept from the user when he uploads it?
Just write down it as info for the user.
Also, mention the file types that user can upload.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan Apologize for the delay about this issue , will working on it Next week nchallah

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
> * Captcha keeps the previous values
Done.

**Comment by HeshamHassan** [comment]
The below points is not finished yet:
> * [ ]  City fields must be DDM.
> * [ ]  Uploaded Files properties.

They are at the main issue.

**Comment by HeshamHassan** [comment]
As agreed in the meeting between @mohamedMahdyCc and @HeshamHassan today..
This feature is moved to a new issue. 
- City fields new issue number is: #250
- Uploaded Files properties new issue number is: #251
