### ISSUE TITLE
ATP Activation by Admin

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#211]
As an admin role... I'm trying to approve the new ATP. But I couldn't!
- [ ] How to activate some inactive ATP?

![image](https://user-images.githubusercontent.com/11155105/47654245-70949680-db9b-11e8-8237-176640c1b5f6.png)

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
edit organization and check **status** checkbox.

**Comment by HeshamHassan** [comment]
Done
