### ISSUE TITLE
Pre and Post Assessments

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#212]
As the Pre&Post Assessments has been published, Kindly guide how to access, handle and activate.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Now,  I can see the course assessment and I created 1 pre assessment and 1 post assessment.
- [x] How can I run the pre assessment 
- [x] How can I run the post assessment 

_Note: I careated them to course: "MANAGING PROJECTS: FIRST STEPS FIRST"_

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by Ali-Galal** [comment]
@ahmedelbougha high priority please

**Comment by Ali-Galal** [comment]
@ahmedelbougha any update?

**Comment by HeshamHassan** [comment]
1- URL for start an assessment: http://skillsbuilderpro.com/courses/exam/5
- [x] The URL works only with Admin. Other roles give "Access denied"
- [x] User must have a link or a button to start the pre-assessment with every single course.
- [x] User must have a link or a button to start the post-assessment with only his purchased course.
- [x] The page contains only the word "EXAM" ![image](https://user-images.githubusercontent.com/11155105/48544221-3124b480-e8d4-11e8-81ce-95f67a32f42b.png)

2- URL for assessments results: http://skillsbuilderpro.com/courses/myexams
- [x] The URL works only with Admin. Other roles give "Access denied"
- [x] User must have a link, a button or in his menu to access his assessments results.
- [x] The assessment result details page has a completely wrong message. ![image](https://user-images.githubusercontent.com/11155105/48544485-bd36dc00-e8d4-11e8-9a31-e246b3813dc1.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
The user (Student) can see the assessments now as a new tap under each course resourses.
But he cannot access them.
![image](https://user-images.githubusercontent.com/11155105/48692470-3a20c900-ebe7-11e8-99ee-61cf7b0e1ec2.png)

**Comment by HeshamHassan** [comment]
Any update?

**Comment by LamiaSalah** [comment]
@ahmedelbougha 
- [ ] please note that also the English content does not appear only showing the Arabic ones as attached

![image](https://user-images.githubusercontent.com/37042927/49155801-84f7ba80-f324-11e8-90b7-bda8a80c7989.png)

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan access denied issue resolved!

**Comment by HeshamHassan** [comment]
Thanks Mohamed. My issues have done.
the rest is one point from @LamiaSalah : the question contents.
Welcome to the team.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah working on this nchallah

**Comment by mohamedMahdyCc** [comment]
> Thanks Mohamed. My issues have done.
> the rest is one point from @LamiaSalah : the question contents.
> Welcome to the team.

Thanks @HeshamHassan  ^^ , yes working on the question contents issue

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan @ahmedelbougha 
Done! and merged it should be on the live server today nchallah

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan @ahmedelbougha 

please check and close this issue if done!, it's important to close the done issues please to avoid confusing please and focus on remaining issues ^^

**Comment by LamiaSalah** [comment]
@confirmed
