### ISSUE TITLE
SBP Arabic Version

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#213]
I want to test the Arabic version of the portal.
So, I need your guidance; how to access the Arabic interface.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by Ali-Galal** [comment]
@ahmedelbougha high priority please

**Comment by Ali-Galal** [comment]
@ahmedelbougha Any Update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.
