### ISSUE TITLE
Training Manager Registration Form Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#215]
The registration is on 2 stages if I have any incorrect data the registration transfer me to the next page and after I finish it redirects me to the incorrect data in the previous page.

**Comment by HeshamHassan** [comment]
- [ ] The next button must not move me to the next tab if there is a missing data.
- [ ] The previous button must not move me to the previous tab if there is a missing data.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by LamiaSalah** [comment]
@ahmedelbougha please also find below some areas that need modifications:

- [ ] The address fields are incomplete | Add State in front of the   field after US, which is where the state will be; Add a City Field and a Zip   code field after Address 1 and Address 2
- [ ] Areas of expertise only allow for one selection. Many trainers will have more than one area of   expertise, please make this a checkbox list,   check all that apply
- [x] The Instructor Statement is missing please add it

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan ok will working on this

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?
