### ISSUE TITLE
My Profile Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#216]
When a user accesses his profile, he will find a picture placeholder at the top left of the page. 
![image](https://user-images.githubusercontent.com/11155105/48469169-1f251200-e7ff-11e8-8b6c-4c65c635114b.png)

- [x] Activate the picture insertion in all forms.
- [x] If the user did not add his picture, make an avatar as default.
![image](https://user-images.githubusercontent.com/11155105/48470047-74622300-e801-11e8-9a67-93ebc9b5ea92.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan very sorry for late reply , working on this

**Comment by mohamedMahdyCc** [comment]
> * If the user did not add his picture, make an avatar as default. *ok for this*
 If the user did not add his picture, make an avatar as default. `please what you mean by this one`

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha 

Done! , please confirm and close

**Comment by HeshamHassan** [comment]
Not yet. 
![image](https://user-images.githubusercontent.com/11155105/50071266-354d3600-01e2-11e9-9c70-cfe9988ade44.png)

Also:
- [x] How can I add/remove this picture?

**Comment by mohamedMahdyCc** [comment]
![image](https://user-images.githubusercontent.com/40764593/50291878-66469880-0478-11e9-8e1d-ff95d5c96d5f.png)

@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan
Done! please confirm and close

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
This feature "Picture: Browse" is not available to all registration forms.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
