### ISSUE TITLE
User Private Training Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#217]
When some user tries to reserve a private training session, the reservation page - preferred date field is caching. 
![image](https://user-images.githubusercontent.com/11155105/48472825-27ce1600-e808-11e8-85fc-82a46aaee416.png)

- [x] Remove caching from the "Preferred Date" field.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan sorry hisham for late reply, will check today and reply you ASAP nchallah

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan done , please confirm and close

http://skillsbuilderpro.com/quote/training/private/23

**Comment by HeshamHassan** [comment]
Done.
