### ISSUE TITLE
User Public Training Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#218]
When some user tries to reserve a public training session, the courses page has expired courses. 
Also I can register in that expired courses.
![image](https://user-images.githubusercontent.com/11155105/48474717-2f8fb980-e80c-11e8-9217-b2a9b57c5ed5.png)

- [x] Stop registring on any expired course.
- [x] Remove expired courses from the reservation page.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Update me Pls.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
