### ISSUE TITLE
Social Media Sharing Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#219]
The social media buttons act like that:
* Twitter button opens SBP account @ twitter. 
* LinkedIn button opens SBP account @ LinkedIn. 
* Facebook button opens SBP account @ Facebook. 
![image](https://user-images.githubusercontent.com/11155105/48713086-80464e80-ec20-11e8-9678-0bad9a1b5d9d.png)

It must act like that:
- [x] Twitter button share the concerned course @ twitter. 
- [x] LinkedIn button share the concerned course @ LinkedIn. 
- [x] Facebook button share the concerned course @ Facebook.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc**
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan please explain with more info what is the issue here ?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Let's discuss this issue in our next meeting.

**Comment by MuhammedMahdy** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
