### ISSUE TITLE
SBP-22: [NEW FEATURE] Create ATP Calendar

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#22]

**Comment by solimansamy** [comment]
We need to add a new column `Calendar` here http://certigate.camelcasetech.com/organizations/atps Should link to a new page like this http://certigate.camelcasetech.com/courses/calendar

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/8

**Comment by solimansamy** [comment]
@AbdElmoneimMohamed ATP **should not** have calendar if it has no course event, we need to remove the icon of calendar here https://camelcase.slack.com/files/U5VC46Z6F/F7PNYCA58/screenshot_from_2017-10-25_16_48_58.png

When I click on `bothDummy` calendar, it goes me to empty page because it has no course event.
