### ISSUE TITLE
Edit/Modify Old Users' Profiles

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#220]
I cannot edit or modify any user profile.
Whatever the user's role, edit profile page appears with one-page form without tabs (Old form view)
Also, the forme labeled: "New User"
![image](https://user-images.githubusercontent.com/11155105/49078020-eef16080-f24d-11e8-8122-93974cd2e8fc.png)

**Comment by HeshamHassan** [comment]
Any update?
It is an important issue.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal working to fix this

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @Ali-Galal @ahmedelbougha Done! please confirm and close

**Comment by HeshamHassan** [comment]
Admin profile OK

**Comment by HeshamHassan** [comment]
Other profiles OK
