### ISSUE TITLE
Press Pages

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#221]
@ahmedelbougha Please 

- [x] make the summary in the press release optional

 and 

- [x] photo in the press release optional

 in the press pages insert form.

@ahmedelbougha 

- [x] how can I access the press release's pages?

**Comment by LamiaSalah** [comment]
@ahmedelbougha we need this issue to be handled at the soonest please, let's discuss tomorrow urgently.

**Comment by Ali-Galal** [comment]
@ahmedelbougha I need your immediate attention to this issue 
how can I access the press release's pages?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is the page in frontend, obviously it needs theming to match SkillsBuilder frontend design. 
http://skillsbuilderpro.com/cms/press-release

**Comment by Ali-Galal** [comment]
@ahmedelbougha So?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
So, we will do it ya Ali En Shaa Allah :)

**Comment by LamiaSalah** [comment]
@ahmedelbougha could you please advise when it'll be finished?

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah tomorrow nchallah,

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha 
Done! and merged it should be on the live version today nchallah

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc what about this page http://skillsbuilderpro.com/cms/press-release the main Press realeases one and its theme?

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc what about this page http://skillsbuilderpro.com/cms/press-release the main Press realeases one and its theme?
@LamiaSalah @ahmedelbougha 
its done and live now on new url http://skillsbuilderpro.com/press-release , also i added `unsubscribe` button instead of empty area just wait to merge and push live

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc thank you. This main page does need to be the same as the regular press release page. As discussed it needs to include the links to the press releases that will be created. It needs to be created as a press release, not a Page. This is urgent

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah 
The press releases page is different than the regular pages, http://skillsbuilderpro.com/press-release is supposed to contain a list of any content page that you create it as press release.
To create new press release you need to go to admin -> CMS -> Pages, click `Create new Page` button, then change the `Type` of that page to be `Press Release`

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc so any page created under Press release category will be shown in this page?

**Comment by mohamedMahdyCc** [comment]
![ae5a8d10-181b-4baf-a673-2dda6564654b](https://user-images.githubusercontent.com/40764593/49696598-c4d86080-fbb4-11e8-8ceb-fdc258e23daa.jpeg)
yes but to confirm please check attachment , press release just page type not category

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah please confirm and close

**Comment by LamiaSalah** [comment]
Confirmed

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc The fields of the photos and summary were supposed NOT to be mandatory, however, on creating a new release, the system still refuses to save unless they are added!

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha its done now please confirm and close
http://skillsbuilderpro.com/press-release

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  the issue is fixed, but after posting the release, there's a place for the image still available in the live page. Please check  this 

![image](https://user-images.githubusercontent.com/37042927/49797094-1ca6d100-fd47-11e8-8dd2-8ea80b8a33a3.png)

**Comment by LamiaSalah** [comment]
Please change the URL to be Press Room rather than Press Release

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah thanks for info working on this

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah Done pelase confirm and close 
http://skillsbuilderpro.com/press-rooms

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  thank you, the image issue has been fixed, however:

- on clicking the press room from the menu either in English or Arabic, an error occurs and page doesn't show 
![image](https://user-images.githubusercontent.com/37042927/49805466-da3cbe80-fd5d-11e8-9752-c71f990fb4dd.png)

- Also, the alignment of title تصريحات صحفية and text need to be right in Arabic
- The text at the bottom read more need to be إقرأ المزيد

**Comment by mohamedMahdyCc** [comment]
thanks @LamiaSalah for info i checked the menu urls from here: http://skillsbuilderpro.com/cms/menuitem?title=&directUrl=press-rooms&type=&menu=&status=&filter=%D8%AA%D8%B5%D9%81%D9%8A%D8%A9,
and updated the urls to press-rooms please check now

**Comment by LamiaSalah** [comment]
Thanks, could you please remove the flowers photo in the main press page and the press release page

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah Done!

**Comment by LamiaSalah** [comment]
Thanks, Just the Arabic allignment issue is left

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah ok working on this

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
- [x] How to add a new post or an essay to the press room page?

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah 
press rooms style fixed now please check 
http://skillsbuilderpro.com/press-rooms

**Comment by mohamedMahdyCc** [comment]
> **@mohamedMahdyCc**
> 
> * [x]  How to add a new post or an essay to the press room page?

@HeshamHassan @LamiaSalah 
![49696598-c4d86080-fbb4-11e8-8ceb-fdc258e23daa](https://user-images.githubusercontent.com/40764593/49879702-3ae9fb00-fe33-11e8-8f46-350cf8e42bc5.jpeg)
basically from any page just change the page type to `press release`

please confirm and close this issue

**Comment by HeshamHassan** [comment]
Form my side, it's ok. Done.
**@LamiaSalah** : Please check if you have something in this issues.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan @ahmedelbougha 
I think all is done now please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  it is still Press Room**s,** it should be Press Room 
also, the Arabic should be غرفة الصحافة

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah ok working on this ...

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha 
Done! please confirm and close

http://skillsbuilderpro.com/press-room

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc the page title is fixed, while the menu name in the drop down menu is still Press Rooms, also the link need gives error from the menu. I'm not sure why this is taking so long to be fixed!

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc the page title is fixed, while the menu name in the drop down menu is still Press Rooms, also the link need gives error from the menu. I'm not sure why this is taking so long to be fixed!

@LamiaSalah @ahmedelbougha 
we already done, i think you need to update the menu name from admin panel http://skillsbuilderpro.com/cms/menuitem , i updated it for you now

@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
please confirm and close

**Comment by HeshamHassan** [comment]
- [ ] The press room is nor present at the footer.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc could you please add it in the footer?

**Comment by mohamedMahdyCc** [comment]
> * [ ]  The press room is nor present at the footer.

@LamiaSalah @HeshamHassan @Ali-Galal  ok will working on this as Enhancement ok ?
if yes please close this issue and create new one with the label `Enhancement`

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
I think it is a fixing process of the footer.

**@Ali-Galal** 
Kindly advice.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc This is relevant to the same issue about the footer, it's just an edit and not an enhancement.

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc This is relevant to the same issue about the footer, it's just an edit and not an enhancement.

ok @LamiaSalah please close this issue and keep the footer request` in the relevant issue
