### ISSUE TITLE
Arabic Format

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#222]
The layout of the Arabic pages in the Learning objectives section is not correct, the title appears next to the added text instead of being at the top.

And the spaces are not fixed at the bottom

![image](https://user-images.githubusercontent.com/37042927/49155397-82489580-f323-11e8-98c7-4ced79d76e3f.png)

Also, the order of the text in the course days need to be fixed

![image](https://user-images.githubusercontent.com/37042927/49156020-06e7e380-f325-11e8-8bc4-bc7e3b943d7d.png)

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
let's discuss this in our phone call today En Shaa Allah.

**Comment by LamiaSalah** [comment]
@ahmedelbougha  
OK

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Kindly update the issue status.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
ok will working n this ASAP

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
