### ISSUE TITLE
Building an Online Business - Purchasing Trainer Guide Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#225]
- I logged on as a trainer. 
- I went to the learning path: Small Business Builder
- I clicked on the course: Building an Online Business
- I chose the resources and clicked to purchase the trainer guide.
- The following message appeared: 
![image](https://user-images.githubusercontent.com/11155105/49340460-2d718b80-f651-11e8-8440-27a6a6d56416.png)

- [x] Kindly check and solve.

**Comment by HeshamHassan** [comment]
Any update?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan ok will check and reply you tomorrow nchallah

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Any update?

**Comment by mahmoud-hussien1** [comment]
@HeshamHassan 
due to fix this issue, we need to delete all products and orders on estore then recreate the products.
**Note**: **SkillsBuilder resources** won't be deleted so, any resource file such as (flipping books, pdf ...etc) won't be deleted (just orders will be deleted).
is that okay with you?

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
Kindly check this issue.

**Comment by LamiaSalah** [comment]
@mahmoud-hussien1  please clarify what do you mean by order will be deleted and what exactly will be deleted?

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah there are orders and products on estore already have been created.
those orders and products will be deleted and products will be recreated to solve this issue.
is that okay.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah please close this issue if done

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc in order to confirm I need to know more details about what will be deleted.

**Comment by Ali-Galal** [comment]
> @HeshamHassan
> due to fix this issue, we need to delete all products and orders on estore then recreate the products.
> **Note**: **SkillsBuilder resources** won't be deleted so, any resource file such as (flipping books, pdf ...etc) won't be deleted (just orders will be deleted).
> is that okay with you?

@mahmoud-hussien1 we don’t have any problem to delete any purchasing orders at mean time, but don't delete any products before our confirmation.

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal @HeshamHassan OK, Can i remove products and recreate them?
**Note**: resource files won't be deleted but product.

**Comment by Ali-Galal** [comment]
@mahmoud-hussien1 if you are going to recreate them without any data losing, go ahead.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
