### ISSUE TITLE
Learning Paths for Arabic Courses 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#227]
@ahmedelbougha as discussed, the Learning Paths in the Arabic Courses page, appears in English as attached

![image](https://user-images.githubusercontent.com/37042927/49695266-40301700-fba1-11e8-9522-04d400b346a1.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha Done please confirm and close
http://skillsbuilderpro.com/courses

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
