### ISSUE TITLE
SBP-23: [EXCEPTION] Undefined property: Organizations\Entity\Organization::$type in Organizations controller

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#23]
Error Stack here https://camelcase.slack.com/files/U5VC46Z6F/F7ELNR3EC/-.txt

**Comment by solimansamy** [comment]
When trying to delete an ATP http://certigate.camelcasetech.com/organizations/atps

**Comment by ahmedelbougha** [comment]
fixed
