### ISSUE TITLE
Pages unsaved

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#230]
@mohamedMahdyCc the Pages still unsaved. Trying to edit the Courses page again but changes are not saved. This is urgent, please

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah ok will check ...

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah it working fine with me can you send more details please , what you try to edit ? which page ? link please

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah please send link for this page to check  ?

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc http://skillsbuilderpro.com/Training/Courses/

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  Could you please also remove the one line gaps in all the addresses?

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah i just check this feature now and it working fine with me , can you please send more details about the issue, what you try to update in `courses` page ?

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed it's working now
