### ISSUE TITLE
Upload files Issue

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#233]
When asking for uploading a file (Ex. Bio) the system uploads the file first then checks for the type if compatible or not.
- [x] System must check for the file type first. If it is compatible then proceed to upload, else give a popup message.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @ahmedelbougha  
ok working on this ...

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
we just consider the file format here when click `choose file` the file explorer should show files with the needed format
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done
