### ISSUE TITLE
Trainers' Registration form 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#234]
@ahmed
Please fix  the following in the Trainers' form:

- Make the default number a US number
- Add State in front of the field after US, which is where the state will be; Aa Zip code field after Address 1 and Address 2
- Add more spaces for Education

**Comment by Ahmed** [comment]
Me?

**Comment by LamiaSalah** [comment]
@ahmedelbougha

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah ok will working on this next week nchallah

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirm please go ahead

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
