### ISSUE TITLE
SEO for pages categories courses

### ISSUE THREAD

**Issue by mohamedMahdyCc** [camelcasetechsd/skillsbuilder#235]

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please advise what this is about

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc please advise what this is about
@LamiaSalah 
in cms -> pages -> edit 
there are 4 new inputs for Search Engine Optimization , will need to fill this inputs to got top ranks with google results

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
 please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  what is SEO description?

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Kindly provide a demo of how to use this feature as a creator for the courses and as a user.

**Comment by mohamedMahdyCc** [comment]
> **@mohamedMahdyCc**
> Kindly provide a demo of how to use this feature as a creator for the courses and as a user.

i remember i replied on this in our meeting last days , please close if this done, thanks

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 

> i remember i replied on this in our meeting last days , please close if this done, thanks

Yes, you did in oral. But, I couldn't do it. 
I made a search for some of training courses names and get nothing. 
So, kindly show me how to use it.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please advise so we can close this issue
