### ISSUE TITLE
Contact Us Page -Arabic Section

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#236]
Make "Contact Us" page a dynamic page.

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
after login as admin you can controll the contactus location from this link: http://skillsbuilderpro.com/locations
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc I want tohave access to make changes to the already created page 'Contact Us' not create new locations please

**Comment by MuhammedMahdy** [comment]
in CMS 
   Menus
   Menu Items
  Pages
  **Locations**
http://skillsbuilderpro.com/locations
you have to add the old location as new locations to appear in this update

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  confirmed

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc please note that the addresses in the Arabic section need to be in Arabic, also phone numbers, and all commands and tabs. ie: Submit

**Comment by mohamedMahdyCc** [comment]
> @mohamedMahdyCc please note that the addresses in the Arabic section need to be in Arabic, also phone numbers, and all commands and tabs. ie: Submit
@LamiaSalah 
done please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc the US address is still in English. Please also replace the dashes in the other 2 addresses with commas.

**Comment by HeshamHassan** [comment]
**@LamiaSalah** 
> @mohamedMahdyCc the US address is still in English. Please also replace the dashes in the other 2 
addresses with commas.

We can edit the addresses through this URL: http://skillsbuilderpro.com/locations

**Comment by HeshamHassan** [comment]
Done.
