### ISSUE TITLE
Press Releases

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#238]
@mohamedMahdyCc In the press release page, the send to a friend button is not working and the download button gives and error message
also we need to add the release year button to allow narrow the presses search.

**Comment by MuhammedMahdy** [comment]
@HeshamHassan will check the `send to friend` button and i checked the download button and its working

**Comment by HeshamHassan** [comment]
**@MuhammedMahdy** 
Download bottom is working, but with Admin role only.

**@Ali-Galal** : Kindly advice: Is Download feature must be available for guests? or only for the registered roles?

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan 
`send to friend` button fixed now please check and close if done

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
I sent the post to my email "hhassan@thinkcsi.com" this morning, but I did not receive it yet.

**Comment by MuhammedMahdy** [comment]
@HeshamHassan as i mentioned before that , this is a aserver issue , we need a correct mail server data to fix this

**Comment by MuhammedMahdy** [comment]
@LamiaSalah 
`also we need to add the release year button to allow narrow the presses search.` 
need more details about this please

**Comment by HeshamHassan** [comment]
> @HeshamHassan as i mentioned before that , this is a aserver issue , we need a correct mail server data to fix this

**@Ali-Galal** 
Kindly advice.

**Comment by HeshamHassan** [comment]
@mohamedMahdyCc 

> @LamiaSalah
> `also we need to add the release year button to allow narrow the presses search.`
> need more details about this please

- [ ] Filter by year.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan 

please create new issue with label `new feature` about this issue `also we need to add the release year button to allow narrow the presses search.` with all needed details

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  I created a new issue with this as requested. However, the download button is now removed and sharing with a friend as well. Please advise.

**Comment by HeshamHassan** [comment]
>> **@MuhammedMahdy**
>> Download bottom is working, but with Admin role only.
>> 
>> **@Ali-Galal** : Kindly advice: Is Download feature must be available for guests? or only for the registered roles?

**@MuhammedMahdy**
Download feature must be available only for the registered users with any role. Guests cannot download.

**Comment by mohamedMahdyCc** [comment]
> > > **@MuhammedMahdy**
> > > Download bottom is working, but with Admin role only.
> > > **@Ali-Galal** : Kindly advice: Is Download feature must be available for guests? or only for the registered roles?
> 
> **@MuhammedMahdy**
> Download feature must be available only for the registered users with any role. Guests cannot download.

@HeshamHassan working on this

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan @LamiaSalah 

Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  @Ali-Galal Done
