### ISSUE TITLE
Message for contact us page

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#239]
We need to add a thank you message after you submit your request that your message submitted successfully with an automatic email stating that my request is in progress

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah kindly prepare this message and email template.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  
Thank you for contacting us. Your request has been submitted successfully. We'll look into it shortly and get back to you within 24 hours.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah 

And in arabic ?

**Comment by LamiaSalah** [comment]
شكراً للتواصل معنا. لقد تم إرسال طلبك بنجاح و سوف نقوم بالنظر فيه و الرجوع  إليك خلال 24 ساعة

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
