### ISSUE TITLE
SBP-24: [NEW FEATURE] The training provider (training manager) and/or the trainer/instructor and/or student can review the resources and the material if they paid for it

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#24]

**Comment by solimansamy** [comment]
Related to #25

**Comment by solimansamy** [comment]
**Frontend Features** 
- Each user should have a **unique download link** for each format, I'm taking here about `Trainer Kit` and `Student Guide`.
- Training Manager and Instructor can purchase the following
-- Student Guide
-- Trainer Kit
-- Audible

- Student can purchase the following
-- Student Guide
-- Audible

Only subscribers can download materials if they paid for it

**Technical Approach**
1. Create new entity for `subscriber` https://github.com/camelcasetechsd/skillsbuilder/issues/27.
2. We need to encrypt/decrypt download link, see below

```
public static function encrypt($text)
    {
        return str_replace(array('+', '/'), array('-', '_'), base64_encode(openssl_encrypt($text, WWW-DDD-WWW, any-number-of-random-characters, true, any-number-of-random-characters)));
    }
```
```
public static function decrypt($text)
    {
        return openssl_decrypt(base64_decode(str_replace(array('-', '_'), array('+', '/'), $text)), 'WWW-DDD-WWW', 'any-number-of-random-characters', true, 'any-number-of-random-characters');
    }
```
3. If current user is a subscriber then create for him download link on the fly using `encrypt` method and into download action decrypt the parameter sent by GET method using `decrypt` method.

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/14

**Comment by babanesma** [comment]
@badr4php  for any additional queries to be run please create new migration file in `db/migrations`
