### ISSUE TITLE
language tab 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#240]
@mohamedMahdyCc we need to have the language tab only seen by ADMIN not any USER

**Comment by mohamedMahdyCc** [comment]
As **just super** admin i need to access the language switcher

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc yes, no users should have access to the language tab. just the admin only

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
