### ISSUE TITLE
in course - font size in English version

### ISSUE THREAD

**Issue by mohamedMahdyCc** [camelcasetechsd/skillsbuilder#241]
![image](https://user-images.githubusercontent.com/40764593/50476676-a4404100-09d1-11e9-8d4e-1bb6dbcef053.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
