### ISSUE TITLE
Courses links in Learning Paths 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#243]
@mohamedMahdyCc please make the course title in each learning path clickable to take you to course(currently only the tab (More) takes you there)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah Working on this

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc Confirmed
