### ISSUE TITLE
Audio Files

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#246]
@mohamedMahdyCc we should have the option of uploading audio files to the website. I'm not sure where are we at this process, please advise

**Comment by MuhammedMahdy** [comment]
@LamiaSalah please let me know more details about this issue

**Comment by HeshamHassan** [comment]
**@Ali-Galal** 
kindly Advice.

**Comment by LamiaSalah** [comment]
@Ali-Galal Is this something that could be applied on the website or is it linked to Amazon Audio?

**Comment by Ali-Galal** [comment]
@LamiaSalah this is related to the Amazon workflow then we will back to CamelCase for linking
