### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#248]
@mohamedMahdyCc Please add Press Room under About Us in the footer section

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha  
Working on this

**Comment by MuhammedMahdy** [comment]
@LamiaSalah @ahmedelbougha 
please close this issue , footer menu now dynamic so you can control the sorting

**Comment by LamiaSalah** [comment]
@MuhammedMahdy  please advise how this is done from our end.

**Comment by mohamedMahdyCc** [comment]
> @MuhammedMahdy please advise how this is done from our end.

i think we already discussed this in meeting please close if it's ok.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc the issue of linking the footer with the header will not be applied, however, we need to make the footer have the same menu items as the header. Currently there is a difference between both.

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah yes you can add new menu items with the same link and sorting like the header.

to do this job , you have to select the `parent` - **Footer Menu**

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @HeshamHassan @HeshamHassan @Ali-Galal 

https://docs.google.com/document/d/1uIMzRLOgoOsDfKdLei3kgRUPq52fWAXd5uBfJKbyWIs/edit?usp=sharing

here documentation link on how the new dynamic menu feature working

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah  
please close if done

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please give me access to doc. I sent you a request

**Comment by HeshamHassan** [comment]
Footer is now Dynamic. 👍 

**@mohamedMahdyCc** 
The items in the footer have some wrong direction. All links redirect to the "Corporate Profile" page whatever I made the "Menu Item Type" Page, Direct URL or Category.

**Comment by mohamedMahdyCc** [comment]
> Footer is now Dynamic. 
> 
> **@mohamedMahdyCc**
> The items in the footer have some wrong direction. All links redirect to the "Corporate Profile" page whatever I made the "Menu Item Type" Page, Direct URL or Category.

@HeshamHassan @Ali-Galal 

Apologize for this mistake , fixed now please check and close if it done

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
The following links are not working:
- Trainer's Hub
- Why Train with SBP?
- Knowledge Assessments
- Membership - Individuals
I checked their configuration and the link in each menu item is correct...
![image](https://user-images.githubusercontent.com/11155105/51597019-4e48b580-1f0b-11e9-81a8-b1bc7ee947bb.png)

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by Ali-Galal** [comment]
@mohamedMahdyCc the footer is ok, but it should be from right to left when it will be in Ar interface.

**Comment by Ali-Galal** [comment]
reminder

**Comment by HeshamHassan** [comment]
> **@mohamedMahdyCc**
> The following links are not working:
> 
> * Trainer's Hub
> * Why Train with SBP?
> * Knowledge Assessments
> * Membership - Individuals
>   I checked their configuration and the link in each menu item is correct...
>   ![image](https://user-images.githubusercontent.com/11155105/51597019-4e48b580-1f0b-11e9-81a8-b1bc7ee947bb.png)

Some of the footer links still need to be adjusted:
- Marketing Pro
- Why Train with SBP?
- Knowledge Assessments
- Membership - Individuals

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan
all of this links Marketing Pro
Why Train with SBP?
Knowledge Assessments
Membership - Individuals this one need to update it's resource link
working now , what you mean by adjusted ??

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
the following are the results which I got when using the selected footer items:
**Knowledge Assessments:**
![image](https://user-images.githubusercontent.com/11155105/52176433-cd6ba280-27c3-11e9-9cee-6f089885139f.png)
**Membership - Individuals**
![image](https://user-images.githubusercontent.com/11155105/52176454-10c61100-27c4-11e9-8745-1b5d9b7f7d4a.png)

**Marketing Pro** and **Why Train with SBP?** are working good now.

**Comment by mohamedMahdyCc** [comment]
@HeshamHassan this pages need to be activated at first 

![image](https://user-images.githubusercontent.com/40764593/52178608-753f9b00-27d9-11e9-86bf-46786399aa15.png)

**Comment by HeshamHassan** [comment]
**@MuhammedMahdy** 
I made the necessary modifications.
They all now working good.
