### ISSUE TITLE
SBP-25: [NEW FEATURE] Resources will be Changed to Format type

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#25]
As the following:
- ILT Format:
i. Trainer Kit
ii. Student Guide
- Audible
- e-Learning (in last Phase)

**Backend Features**
We will change the resources area here http://certigate.camelcasetech.com/courses/resources/new/1.
We should have for now 3 types of resources
- `Trainer Kit`.
- `Student Guide`.
- `Amazon Audible`.

Check the form here
https://camelcase.slack.com/files/U5VC46Z6F/F7GPX33CN/screenshot_from_2017-10-10_11_36_39.png

If admin chooses `Amazon Audible`, then he can see URL text box instead of `choose file`

`Price` text box should be added for all types.

**Technical Approach**
- `Trainer Kit` and `Student Guide` should be saved as current state did.
- `Amazon Audible` in this resource we will save the link in `file` field. We should update `COURSE RESOURCES` view.
- Admin should create only one resource for each type, we should add restriction here in form validation.
- When admin creates new course, he creates a new product `A` in eStore with option `course event`. For resources we should **clone** product `A` then create product `B` with option `course resource`

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/10

**Comment by badr4php** [comment]
- [x] If course resource has type of "Amazon Audible " it can't be removed .it only disappear from page but still found in database

- [x] When remove course resource it removed only from skill builder but still found in opencart

**Comment by badr4php** [comment]
When remove course resource  it removed only from skill builder but still found in opencart

**Comment by solimansamy** [comment]
One task is remaining here #30
