### ISSUE TITLE
Forms Issues : City fields

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#250]
- [ ] City fields must be Drop Down Menu.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
It is not a new feature. It is a **BUG**.
It was available before applying the new forms and disappeared with the applying of them.

**Comment by MuhammedMahdy** [comment]
@ahmedelbougha 
Kindly Advice

**Comment by Ali-Galal** [comment]
@ahmedelbougha we need it DDM as it was in the old registration
