### ISSUE TITLE
Forms Issues : Fields Description and Information

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#251]
- [x] Add description and properties as a hint for Uploaded Files fields. (Allowed Files type and maximum size)
- [x] When start browsing, filter the window contents to the concerned files only.

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
