### ISSUE TITLE
Registration Forms - Arabic Fields

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#252]
@mohamedMahdyCc  Remove Arabic fields for names from English section and remove English from Arabic section.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
All the marked in search fields. they are duplicated data. They are 5 fields:

**English Form:** 
1. First Name in Arabic
2. Middle Name in Arabic
3. Last Name in Arabic
4. Address Line 1 in Arabic
5. Address Line 2 in Arabic

![image](https://user-images.githubusercontent.com/11155105/50825112-40ab0180-1349-11e9-8f10-8c99df38b582.png)

**Arabic Form:**
1. الإسم الأول باللغة العربية
2. الاسم الأوسط باللغة العربية
3. الإسم الأخير باللغة العربية
4. السطر الأول للعنوان العربي
5. السطر الثاني للعنوان العربي

![image](https://user-images.githubusercontent.com/11155105/50825224-9089c880-1349-11e9-82f9-429c9623b8d6.png)

**Comment by MuhammedMahdy** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  please note that the rest of the fields in the Arabic form are all in English at the bottom of the page. 
![image](https://user-images.githubusercontent.com/37042927/50907215-804c1900-142f-11e9-80cb-7ca83db35500.png)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@MuhammedMahdy Still Bio and Bio description in English. Please note that this section of ' Description' is not clearly stated as I'm not sure what it will be used for in all fields.

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Kindly update.

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc  confirmed
