### ISSUE TITLE
Courses Names in Arabic

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#257]
@mohamedMahdyCc the Courses Titles and all fields are still in English in the Internal pages 

http://skillsbuilderpro.com/courses/assessments/53 

![image](https://user-images.githubusercontent.com/37042927/51169404-7f463c00-18b4-11e9-8e87-d97a75709a53.png)

**Comment by HeshamHassan** [comment]
**@mohamedMahdyCc** 
Each course has its Arabic name. So, kindly do the following action:
- [x] Automatically show corse's Arabic name everywhere when using Arabic interface.

**Comment by mohamedMahdyCc** [comment]
@ahmedelbougha @Ali-Galal @HeshamHassan 
Done! please confirm and close

**Comment by HeshamHassan** [comment]
Done.
