### ISSUE TITLE
SBP-26: [ISSUE] We should remove product from cart when user cancels his enrollment into course

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#26]

**Comment by solimansamy** [comment]
Check cart remove here public/estore/catalog/view/javascript/common.js:200

**Comment by solimansamy** [comment]
Check cart remove route module/EStore/src/EStore/Service/ApiCalls.php:38

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/9

**Comment by babanesma** [comment]
@badr4php please correct spelling `cart` instead of `crat`

**Comment by solimansamy** [comment]
@badr4php Failed QA
