### ISSUE TITLE
Create new entity for Subscriber

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#27]
**CRUD**
Table Name: subscriber

Table Fields: 
- id
- user_id
- reference_id
- transaction_id
- type
- status
- created
- modified

**Comment by solimansamy** [comment]
We should have an entity for Course Event Subscription here module/Courses/src/Courses/Entity/CourseEventSubscription.php. We need to reuse this

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/11
