### ISSUE TITLE
Access to Dashboard 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#273]
@mohamedMahdyCc we need to have a direct access to the backend (Dashboard) without then need to go through different menu items. Please create a dashboard landing page with a button to it accessible from the admin menu.

**Comment by mohamedMahdyCc** [comment]
@Ali-Galal @LamiaSalah @ahmedelbougha please add more description what you expect to see with this dashboard, then confirm to add estimation for this issue

fox example: 
- show user total for every user by role.
- add fast shortcuts for the internal system pages.
- add charts to show you statistics report for the website usage or any thing you want.
