### ISSUE TITLE
Student Registration Form 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#275]
@mohamedMahdyCc The Student Registration form in Arabic still have Fields in English e.g( Full time employee, New graduate, etc...)

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal
Done! please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc can you send me the link please? when I click www.skillsbuilderpro.com/regitser i go to the new user page not the main page that has the three categories.

**Comment by Ali-Galal** [comment]
@LamiaSalah  http://skillsbuilderpro.com/register

**Comment by mohamedMahdyCc** [comment]
@LamiaSalah @ahmedelbougha @Ali-Galal @HeshamHassan 
Done!, its redirect now to the new form
 please confirm and close

**Comment by LamiaSalah** [comment]
@mohamedMahdyCc confirmed
