### ISSUE TITLE
eStore administration

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#279]
![capture](https://user-images.githubusercontent.com/36264944/52208229-f0b05380-2890-11e9-8084-758c773d8aba.PNG)

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal 
Please write the scenario that get this warning to you.

**Comment by Ali-Galal** [comment]
@mahmoud-hussien1 just try to edit one of the orders

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal I will check that. sorry for late response.

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal please go to esore admin.
in side menu.
go to  System > Users > API.
click to edit API row that appear in this page.
in edit page, find IP Address tab. then add your IP Adress to this page.

**Comment by mahmoud-hussien1** [comment]
@Ali-Galal 
Please Close if it's fixed.

**Comment by Ali-Galal** [comment]
done
