### ISSUE TITLE
SBP-29: [ENHANCEMENT] Create one configuration file contains DB credentials

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#29]
**Current State**
Each module has its own config as follow

- [x] eStore reads config from here `public/estore/config/`
- [x] zend framework reads config from here `config/autoload/`
- [x] DB Seeding `phinx.php`
- [x] q2a Seeding `/home/soliman/Projects/skillsbuilderpro/public/q2a/qa-config.php`
- [x] Forum Seeding `public/forum/config/`

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/21
