### ISSUE TITLE
SBP:32 [NEW FEATURE] Add to registration page some fields

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#32]
Add to the registration page the following fields:
- Video field (allow the user to upload only one video)
- BIO (allow the user to upload his BIO)
- Text area field (with FCK editor) for the BIO

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/16
