### ISSUE TITLE
SBP: 33 [NEW FEATURE] Abillity to deactivate course resources

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#33]
Beside removing course resources, we need to deactivate them. If admin tries to deactivate a course resource, update the following:
- Change its record into skillsbuilder DB to be inactive
- Change its product into estore DB to be inactive as well

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/15
