### ISSUE TITLE
SPB-36 [NEW FEATURE] Add objectives member field in Course entity

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#36]
We need to add a new field to Course entity ar/en when creating and updating likes attached. Also we need to apply `CK editor` for Arabic and English like here http://skillsbuilderpro.com/cms/page/new

**Comment by solimansamy** [comment]
For sql update, please create a migration file here db/migrations/20170307144721_third_parties_apps_themes.php

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/18
