### ISSUE TITLE
SPB-39: [REFACTOR] Create generic upload method

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#39]
We have some redundancy methods are related to upload object, we need to make a generic one for all of them, check below a sample.

- module/Organizations/src/Organizations/Model/Organization.php:388
- module/IssueTracker/src/IssueTracker/Model/Issues.php:117
- module/CMS/src/CMS/Model/Page.php:93
- module/Users/src/Users/Model/User.php:230

**Comment by solimansamy** [comment]
We can generic this method module/Utilities/src/Utilities/Service/File.php:81

**Comment by AbdElmoneimMohamed** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/20
