### ISSUE TITLE
SBP-42: [NEW FEATURE] Ability to upload image for Course entity

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#42]
In the admin add image field to course

**Comment by badr4php** [comment]
when edit course if there is no image it will displayed as broken image.
![broken-image](https://user-images.githubusercontent.com/24792169/32840828-725a630a-ca21-11e7-943b-e8d3fb29f9e2.png)

**Comment by solimansamy** [comment]
@badr4php We can contact the client to provide us with default course image. I will merge as it is.
