### ISSUE TITLE
Missing in new design

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#49]

**Comment by solimansamy** [comment]
- [x] Adjust main menu
- [ ] Upload `x` image.
- [x] Rename title tag to `Skills Builder Pro`.
- [x] Trim course overview in http://skillsbuilderpro.com/courses/calendar
- [x] Solve problem of `getBrief`
- [x] Create a new front-end action for `ATP | ATC Organization`.
- [x] Redesign Organization form.

**Comment by badr4php** [comment]
https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/42
