### ISSUE TITLE
SBP-5: [NEW] Create new modules for categories

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#5]

**Comment by solimansamy** [comment]
We need to create a new module for `Categories`, they are named also as `Learning Paths`.
http://certigate.camelcasetech.com/categories
http://certigate.camelcasetech.com/categories/edit/1
http://certigate.camelcasetech.com/categories/delete/1

**Backend Features**
1. Edit category.
2. Delete category.
3. Assign category to a course.
4. List all categories.

**Frontend Features**
1. Category list page contains all of them.
2. Category details pages contains details about the category and courses assign to it

**CRUD**
Table Name: category

Table Fields: 
- id
- parent_id
- name
- nameAr
- details
- image
- status
- date_added
- date_modified

**Comment by AbdElmoneimMohamed** [comment]
@solimansamy 
https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/5
