### ISSUE TITLE
General issues in SkillsBuilder

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#52]

**Comment by solimansamy** [comment]
- [ ] I can see course details page on `SkillsBuilder` even if the course is deactivated. We need to prevent this.
- [ ] I can enroll in a course even if it's deactivated. We need to prevent this.
- [ ] After deactivate a course, I can't to activate it again. We need need the ability to do that.
- [ ] I have merged PR #14, We need to check it on `development`.
- [ ] The logo need to be smaller and in white (the version that I sent you).
- [ ] The main menu header need to be with less height
- [ ] The main header photos do not transit with the same animation as the template.
- [ ] The photo next to the 4 colored square is missing and replaced with text.
- [ ] Our Projects need to be replaced with (Our Learning Paths)
- [ ] Please add the content sent earlier for each Learning Path
- [ ] Photos added are cropped.
- [ ] Last section should be Top Courses
- [ ] Please add footer with the logo and same lay out as the template.
- [ ] Option of adding a photo to the internal pages on SBP is not working.

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Sorry, that was internal issue, please ignore
