### ISSUE TITLE
Make configuration file to define CURRENT_THEME dynamically

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#53]
We have now the following branches
certiport-development
skillsbuilder-design

Associated to the following domains
http://certiportarabia.com/
http://skillsbuilderpro.com/
http://knowledgeworkerspro.com/

We need to add some configuration so that CURRENT_THEME should be defined dynamically instead of hard coded

**Comment by badr4php** [comment]
touch config/hosts.php
Then put the content below into it
$hosts = [
    [
        "host" => "certiportarabia.com",
        "theme" => "certiport"
    ],
    [
        "host" => "knowledgeworkerspro.com",
        "theme" => "certigate"
    ],
    [
        "host" => "skillsbuilderpro.com",
        "theme" => "skillsbuilder"
    ],
];

function getCurrentTheme($hosts)
{
    $currentHost = $_SERVER['SERVER_NAME'];
    foreach ($hosts as $host) {
        if ($currentHost == $host['host']) {
            return $host['theme'].'/';
        }
    }
    return 'default/';
}

**Comment by badr4php** [comment]
update config.php file add this lines in it
require_once 'hosts.php';
define('CURRENT_THEME', getCurrentTheme($hosts));

**Comment by ahmedelbougha** [comment]
Done
