### ISSUE TITLE
Issues in Skillsbuilder Homepage

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#58]
- [x] Home page need to be amended as follows:                                                                                        - 
      The logo need to be smaller and in white (the version sent eralier).
- [x] The main menu header need to be with less height 
- [x] The main header photos do not transit with the same animation as the template(excluded by Rashad).
- [x] The photo next to the 4 colored square is missing and replaced with text.
- [x] Our Projects need to be replaced with (Our Learning Paths)
- [x] Please add the content sent earlier for each Learning Path(excluded by Rashad)
- [x] Photos added are cropped(excluded by Rashad).
- [x] Last section should be Top Courses
- [x] Please add footer with the logo and same layout as the template.

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/48
