### ISSUE TITLE
SBP-66 - English Photo Upload hidden in Pages

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/skillsbuilder#66]
English photos upload are hidden for CMS Pages create/edit though it's works fine for CMS Press Releases

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/73

**Comment by ahmedelbougha** [comment]
@badr4php 
I still cannot see `Picture` field when I'm using Page as CMS type, please check

**Comment by ahmedelbougha** [comment]
merged
