### ISSUE TITLE
SBP-7: [EXCEPTION] When trying to register, exception related to `longitude` raised

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#7]

**Comment by solimansamy** [comment]
Check exception here

https://camelcase.slack.com/files/U3JJSCKK3/F7CLKD9GV/map-error.txt

**Comment by badr4php** [comment]
PR : http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/2
