### ISSUE TITLE
TTT - Add preview option to courses

### ISSUE THREAD

**Issue by ahmedelbougha** [camelcasetechsd/skillsbuilder#73]
Add preview options courses just like CMS Pages.
Estimated Time: 2 days
Estimated Date: 18/03/2018

Please approve

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/84

**Comment by ahmedelbougha** [comment]
done
