### ISSUE TITLE
Arabic menu

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#74]
The order of the Arabic menu is wrong, it should start from right to left, not like English
Also the font of the titles is very small in Arabic

**Comment by ahmedelbougha** [comment]
Priority 2

**Comment by mahmoud-hussien1** [comment]
http://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/82

**Comment by ahmedelbougha** [comment]
Done
