### ISSUE TITLE
SBP-8: [ENHANCEMENT] Super admin can't deactivate himself

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#8]

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/4

**Comment by babanesma** [comment]
@badr4php if the requested is that the admin can not deactivate **himself** then these changes are slightly wrong 
the changes you provided make no one can deactivate any admin ( or any user who has admin role ) 
change it to check if the $id is the same as logged in user id
