### ISSUE TITLE
Estore 

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#82]
Please note that the e-store page is empty and the courses should be reflected on on that page once created.

**Comment by Ali-Galal** [comment]
any update?

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder..

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Shouldn't you upload the contents of EStore?
