### ISSUE TITLE
SBP Home Page is not working

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#83]
**URL**: http://www.skillsbuilderpro.com/
**Subject**: The Skills Builder Pro. home page is not working.
![image](https://user-images.githubusercontent.com/11155105/38171845-e215bc96-35a9-11e8-8701-efe131308cc2.png)

**Comment by Ali-Galal** [comment]
Dear @ahmedelbougha I need this to be settled before this Tuesday

**Comment by ahmedelbougha** [comment]
done, I made http://www.skillsbuilderpro.com redirecting to http://skillsbuilderpro.com
