### ISSUE TITLE
The website is not working probably on Mac Safari.

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#84]
**URL:** http://www.skillsbuilderpro.com/ 
**Subject:** The website is not working probably on Mac Safari.

**Comment by Ali-Galal** [comment]
Dear @ahmedelbougha I need this to be settled before this Tuesday

**Comment by ahmedelbougha** [comment]
Are you using www.skillsbuilder.com or skillsbuilder.com ?

**Comment by Ali-Galal** [comment]
skillsbuilder.com

**Comment by ahmedelbougha** [comment]
done
