### ISSUE TITLE
Join Chat is not working

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#85]
Join Chat is not working
![image](https://user-images.githubusercontent.com/11155105/38174059-fa2fec90-35cf-11e8-82ee-4d0a05309430.png)

**Comment by ahmedelbougha** [comment]
Priority 7

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by Ali-Galal** [comment]
third reminder

**Comment by ahmedelbougha** [comment]
Date: 2/5/2018

**Comment by Ali-Galal** [comment]
update?

**Comment by ahmedelbougha** [comment]
merged and tested working on production

**Comment by HeshamHassan** [comment]
I tried to work with it. the same situation.
@ahmedelbougha 
Would you advice how to work with it?

**Comment by ahmedelbougha** [comment]
ok

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Login using: `admin`
on another browser login using: `student`

Now, the `student` chat screen you can see list of logged in admins, you can click any of them to start new chat session, at that moment new chat session starts at admin end as well.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Sorry Ahmed, we checked this issue online together, but I tested the chat today and still no admin name at the chat box of the students.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
OK, checking that.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
Waiting for your sign of running the chat feature to start testing.

**Comment by ahmedelbougha** [comment]
Thanks @HeshamHassan 
I will let you know once ready En Shaa Allah

**Comment by Ali-Galal** [comment]
delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by ahmedelbougha** [comment]
Sunday 15th of July

**Comment by HeshamHassan** [comment]
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check with @Ali-Galal

**Comment by Ali-Galal** [comment]
@ahmedelbougha kindly find the chat code 

`
<script type="text/javascript">
window.__lc = window.__lc || {};
window.__lc.license = 10096423;
(function() {
  var lc = document.createElement('script'); lc.type = 'text/javascript'; lc.async = true;
  lc.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'cdn.livechatinc.com/tracking.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(lc, s);
})();
</script><noscript>
<a href="https://www.livechatinc.com/chat-with/10096423/">Chat with us</a>,
powered by <a href="https://www.livechatinc.com/?welcome" rel="noopener" target="_blank">LiveChat</a>
</noscript>
`

**Comment by ahmedelbougha** [comment]
@badr4php please remove old Chat and add the above code instead.

**Comment by badr4php** [comment]
@ahmedelbougha  PR : https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/58/85-third-party-service-to-handel-chat/diff

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
fixed

**Comment by HeshamHassan** [comment]
It's Ok for SBP pages.
But it must appear at all eStore pages too.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
Done
