### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#86]
**URL**:http://skillsbuilderpro.com/sign/in
**Subject**:Sign in page needs to be adjusted. Its appearance is not act well.
There are missing pictures and the header has unsuitable animation.
![image](https://user-images.githubusercontent.com/11155105/38174071-3a462254-35d0-11e8-9bbb-47dc70a84f47.png)

**Comment by ahmedelbougha** [comment]
As agreed with Ali, this is to be closed, since it's related to the theme itself.
