### ISSUE TITLE
User role section in the user profile form

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#87]
**URL:** http://skillsbuilderpro.com/users/edit/14 
**Subject:** User Role section in the user profile needs to be adjusted
Privacy Statement section in the user profile needs to be adjusted
![image](https://user-images.githubusercontent.com/11155105/38174086-8ee16c06-35d0-11e8-8059-4807ae9a6631.png)

**Comment by ahmedelbougha** [comment]
done
