### ISSUE TITLE
User sub menu appears over the menu

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#88]
**URL:** http://skillsbuilderpro.com/users
**Subject:** User sub menu appears over the menu. Cannot access the training manager submenu. It must appear beside not over.
![image](https://user-images.githubusercontent.com/11155105/38174096-c8f1a398-35d0-11e8-9e30-60d85528de81.png)

**Comment by ahmedelbougha** [comment]
Priority 6

**Comment by ahmedelbougha** [comment]
done, please Ctrl+Shift+R to update the styles.
