### ISSUE TITLE
Courses List View

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#89]
**URL:** http://skillsbuilderpro.com/courses
**Path:** Admin> Course> Courses
**Subject:** This report needs some database features: Sort & Filter.
![image](https://user-images.githubusercontent.com/11155105/38174137-9fbf6c48-35d1-11e8-9a01-5a2946f1a40b.png)

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is a new feature. Please confirm, so we can proceed with estimation.

**Comment by Ali-Galal** [comment]
rejected
