### ISSUE TITLE
SBP-9: [NEW FEATURE] User can view the outlines if and only if he provides us his email address.

### ISSUE THREAD

**Issue by solimansamy** [camelcasetechsd/skillsbuilder#9]

**Comment by solimansamy** [comment]
**Technical Approach**

1. When user tries to click on `Course Outlines` tab in course details page, popup should appear asking him to enter his email address and submit.
2. If a user submitted his email address before for this course, popup **SHOULD NOT** appear to him again.
3. We need to check this on server side mode. What I mean is if user submitted before, then render `Course Outlines` data. If user didn't submit before, don't render data.
4. Popup should have text box for email address and button for submit.
5. Create a new action for submitting form data in `Courses` module. After submitting page will reload.

![screenshot from 2017-10-03 17 22 47](https://user-images.githubusercontent.com/9415375/31133372-90ab38f4-a85f-11e7-8505-15d9fb1e1829.png)

**CRUD**
Table Name: email_outlines

Table Fields:
- id
- user_id
- course_id
- user_email

**Comment by badr4php** [comment]
PR : https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/6

**Comment by AbdElmoneimMohamed** [comment]
@badr4php 

- [ ] an email should have backend validation
- [ ] you can access the outline of any course through http://local-skillsbuilder.com/courses/outlines/1 
without enter user email
