### ISSUE TITLE
Arabic Evaluation Template

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#90]
**URL:** http://skillsbuilderpro.com/courses/ev-templates/edit/1
**Path:** Admin> Evaluation Template
**Subject:** Evaluation Template need the Arabic queries.
![image](https://user-images.githubusercontent.com/11155105/38174175-1d8d59f0-35d2-11e8-9c2f-6bd2b673bf29.png)

**Comment by ahmedelbougha** [comment]
@Ali-Galal @HeshamHassan 
Please elaborate more.

**Comment by HeshamHassan** [comment]
This page is not available in Arabic version.
When switching to the Arabic interface, this page still in English.

**Comment by ahmedelbougha** [comment]
done
