### ISSUE TITLE
Evaluation Template Result

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#91]
**URL:** http://skillsbuilderpro.com/courses/ev-templates/edit/1
**Path:** Admin> Evaluation Template
**Subject:** The Evaluation Template need to have a result report and analytical report.

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Evaluation template has nothing to do with course evaluation, it's just template, we will check the course evaluation and let you know.

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by HeshamHassan** [comment]
Reminder...

**Comment by HeshamHassan** [comment]
Second reminder...

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
In order for you to test this issue you have to have a course with evaluation and that course was finished and people start to fill the evaluation of the course.
Did you test the above scenario? If not, I don't know where's the issue?

**Comment by ahmedelbougha** [comment]
@HeshamHassan @Ali-Galal 
Please test the scenario above in order to consider this a valid issue, or close it for now if you cannot.

**Comment by HeshamHassan** [comment]
I just received the sandbox credential 20 min. ago, and will start checking this issue soon.

**Comment by ahmedelbougha** [comment]
OK, please let me know the status.

**Comment by HeshamHassan** [comment]
I could not complete the planned scenario:

- I purchased a course


![image](https://user-images.githubusercontent.com/11155105/42215856-809af7c0-7ec8-11e8-8609-9d0bd991a7a1.png)

- But it did not start when I clicked on "Checkup" link..


![image](https://user-images.githubusercontent.com/11155105/42215860-84bc5d30-7ec8-11e8-8599-c99421eccc9e.png)

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by Ali-Galal** [comment]
@ahmedelbougha update? and delivery date?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 

1. Evaluation in the course setting has been activated.
2. Course scenario has been made. And materials have been sold.
- [x] How can I access the evaluation form as a student or a trainer to fill it?

   - Student name: user15@thinkcsi.com – Course: Building Relationships: The First Step in Sales.
   - Trainer name: user14@thinkcsi.com – Course: Building Relationships: The First Step in Sales.

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
You have to wait until the end date of the course in order to access the evaluation form.
I suggest to make the end date more recent or something in the past.

Also, please don't add any user/pass here, since this is public and can be viewed by anyone, I suggest you to change all the passwords of the users to new ones.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
There are many courses events in calendar that had been reached the end date. 
There are also users enrolled in these courses.
I logged on with different users that enrolled in finished courses.
I cannot reach the evaluation.
I tried to create new events, but I that events did not appear in the users calendar.

**Kindy advice.**

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Please go to 
User menu > my courses 
Click `View more` in front of the course name you can find the evaluate button there.

**Comment by HeshamHassan** [comment]
@ahmedelbougha 
I successfully accessed the course evaluation and fill in it.
So, we have to get back to the main issue: How can I (as Admin, TM or TCA) view the evaluation results?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Check with @Ali-Galal

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
1- Login as admin
2- go to course events
3- click evaluation icon beside course event.

![evaluation-icon](https://user-images.githubusercontent.com/8982139/45438073-77804c00-b6b6-11e8-8289-4ea81e411336.png)

**Comment by HeshamHassan** [comment]
**@ahmedelbougha**
Thanks, I heve found the evaluation Icon.
But I logged in as "user14" and "user15" and the evaluate button is not present for now!!
I checked it before!!! 
So, kindly check and advice.

**Comment by HeshamHassan** [comment]
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment]
@HeshamHassan 
Both user14 and user15 are enrolled in courses that have no evaluation!
Please build the evaluation of those courses first before you can evaluate them.

**Comment by HeshamHassan** [comment]
All Done.
Thanks
