### ISSUE TITLE
Users Bulk Add

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#92]
**URL:** http://skillsbuilderpro.com/users
**Path:** Admin> User> Users
**Subject:** 
- User page must has users bulk add process.
- And if there is a user duplicate button, it will be good.
![image](https://user-images.githubusercontent.com/11155105/38174223-bff5454a-35d2-11e8-8d85-dfdd3a89905e.png)

**Comment by ahmedelbougha** [comment]
@Ali-Galal this is a new feature, please confirm so we can proceed with estimation.

**Comment by Ali-Galal** [comment]
rejected
