### ISSUE TITLE
Arabic learning paths do not view the Arabic contents

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#93]
**URL:** http://skillsbuilderpro.com/categories
**Subject:** The Arabic home page – Learning Paths section: The block with a left side picture can read the Arabic contents very well. But, the block with a right side picture cannot read the Arabic contents and the contents appear in English.
![image](https://user-images.githubusercontent.com/11155105/38174609-75c2ed00-35d8-11e8-90eb-4b1bd1200b17.png)

**Comment by ahmedelbougha** [comment]
Priority 3
This issue in regard to Learning Paths contents in home page

**Comment by badr4php** [comment]
PR: https://git.camelcasetech.com/ahmed.elbougha/skillsbuilderpro/pulls/90

**Comment by ahmedelbougha** [comment]
done
