### ISSUE TITLE
The header has a bad scrolling action

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#94]
The header has a bad scrolling action in all pages. When scroll the page up or down, it makes a small jump that hides some data in the page. Also, gives a bad user indication. 
![image](https://user-images.githubusercontent.com/11155105/38174723-917c4ea4-35da-11e8-8f01-7508922551e8.png)
After one scrolling click:
![image](https://user-images.githubusercontent.com/11155105/38174731-a6bdd35a-35da-11e8-80fe-8b013f5e8434.png)

**Comment by ahmedelbougha** [comment]
The scrolling is related to the theme itself.
we will check the issue of the header hides the title En Shaa Allah

**Comment by ahmedelbougha** [comment]
Priority 8

**Comment by ahmedelbougha** [comment]
closed - not priority.
