### ISSUE TITLE
Photos on each learning paths need to be fixed with proper focus.

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#96]
Photos on each learning paths need to be fixed with proper focus.

**Comment by ahmedelbougha** [comment]
this is an issue related to the sizes of images uploaded from CMS, it has to be with following size:
Width: 292.5px
Hight: 370px

**Comment by Ali-Galal** [comment]
Pixel?

**Comment by ahmedelbougha** [comment]
yes

**Comment by Ali-Galal** [comment]
@ahmedelbougha we did change the image dimensions as your instructions, but still is not fitting
we edit just one for the test @HeshamHassan is going to upload its screenshot

**Comment by HeshamHassan** [comment]
![image](https://user-images.githubusercontent.com/11155105/38558173-fe0d4c72-3cd7-11e8-808d-40c0bc228afa.png)

**Comment by Ali-Galal** [comment]
any update?

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
This is the home page not the learning path page? do you want to check both??

**Comment by Ali-Galal** [comment]
this is the learning path section of the home page, that what I meant

**Comment by Ali-Galal** [comment]
however, both pages have the same issue 😄

**Comment by ahmedelbougha** [comment]
@Ali-Galal 
Agree, but I have made a test of one of Learning Path pages and it was working fine i.e. upload one course image with dimensions Width: 292.5px and Hight: 370px and it was working fine, would you please recheck?

**Comment by Ali-Galal** [comment]
@HeshamHassan check again

**Comment by ahmedelbougha** [comment]
@Ali-Galal @LamiaSalah @HeshamHassan 
Fixed but you need to re-upload the images with new size.
