### ISSUE TITLE
Design 

### ISSUE THREAD

**Issue by Ali-Galal** [camelcasetechsd/skillsbuilder#98]
The following pages need designs as agreed:

- [x] http://skillsbuilderpro.com/Courses
- [ ] http://skillsbuilderpro.com/skillsbuilderpro.com/training/lms
- [x] http://skillsbuilderpro.com/ILT_Courses
- [x] http://skillsbuilderpro.com/audio_books
- [ ] http://skillsbuilderpro.com/elearning
- [ ] http://skillsbuilderpro.com/Membership
- [ ] http://skillsbuilderpro.com/value_pack
- [ ] http://skillsbuilderpro.com/booking
- [ ] http://skillsbuilderpro.com/training
- [ ] http://skillsbuilderpro.com/services
- [ ] http://skillsbuilderpro.com/eStore

**Comment by ahmedelbougha** [comment]
Priority 5
This is already done but needs review and QA before merging.

**Comment by ahmedelbougha** [comment]
Main courses page can be accessed via this URL http://skillsbuilderpro.com/courses/list.
The main courses page and category page contain the filters (All, ILT, Audio), no LMS yet since the resource is not there.

**Comment by ahmedelbougha** [comment]
the rest of the pages are CMS pages, so this issue is not applicable for them
