### ISSUE TITLE
User Profile Editing – Role Agreements

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#99]
**URL:** http://skillsbuilderpro.com/users/edit/14
**Path:** User> User Menu> Users> My Profile> Edit Your Profile
**Subject:**
- [x] The “I agree to…” is not at the same line with its role
- [x] Role # 2 “Student” agreement must be “I agree to Test Center Administrator Statement”
- [x] The Agreement is of Role # 2 is not clickable
- [x] Role # 4 “Proctor” agreement must be “I agree to Proctor Statement”
- [x] The Agreement is of Role # 4 is not clickable
![image](https://user-images.githubusercontent.com/11155105/38186512-12bfcad2-365c-11e8-9a23-25838f8ee9fa.png)

**Comment by ahmedelbougha** [comment]
Fixed with one known issue, roles not aligned with statements but in admin only.
